<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last screening</name>
   <tag></tag>
   <elementGuidId>74049f16-dd5f-4c01-9c22-877990668ac3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(text(),'SCR')])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-section-content-173']/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-section-content-173 > slot[name=&quot;columns&quot;] > flexipage-column2.column.flex-width > div.slds-col.slds-p-horizontal_small.slds-p-vertical_x-small > slot.column > flexipage-field > slot > record_flexipage-record-field.slds-grid.slds-col.slds-has-flexi-truncate > div.slds-grid.slds-size_1-of-1.label-inline > div.slds-form-element.slds-hint-parent.test-id__output-root.slds-form-element_readonly.slds-form-element_horizontal > div.slds-form-element__control > span.test-id__field-value.slds-form-element__static.slds-grow.word-break-ie11.is-read-only > slot[name=&quot;output&quot;] > force-lookup > div.slds-grid > records-hoverable-link.slds-grow.flex-wrap-ie11 > div.slds-grid > a.flex-wrap-ie11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a51f13dd-dd14-47b9-bd36-02c9344c8e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-wrap-ie11</value>
      <webElementGuid>86753619-6925-46a7-b351-49fbbde65e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/r/Screening__c/a0xSu0000000AYrIAM/view</value>
      <webElementGuid>230db898-9ec7-46a5-b96b-4f77e2c2a69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93a00139-5db5-4ad0-aa59-c72cf4cff910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SCR-00557299</value>
      <webElementGuid>4168d4a2-06f7-455e-a0a4-ed29842e46ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(text(),'SCR')])[1]</value>
      <webElementGuid>7f3eec1d-518e-4250-a099-0f6686b1f8cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-173']/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a</value>
      <webElementGuid>546598d9-d745-44a3-b199-4b9b7c588a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/Screening__c/a0xSu0000000AYrIAM/view')]</value>
      <webElementGuid>5b2e6949-f905-436b-93f4-ac108116514f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-component2[7]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/div/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a</value>
      <webElementGuid>997ffca2-ede6-4bd5-8ea2-0967ca00b695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lightning/r/Screening__c/a0xSu0000000AYrIAM/view' and (text() = 'SCR-00557299' or . = 'SCR-00557299')]</value>
      <webElementGuid>871011b4-c472-4f03-86b6-309a8a38832e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
