<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Screening Task</name>
   <tag></tag>
   <elementGuidId>7fb96f5d-15fc-45cc-b48b-27a5c5d04327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@class='subjectLink slds-truncate'])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='upcoming-activities-section-003Su000001A0KkIAK']/div/ul/li/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.subjectLink.slds-truncate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a140a4d9-62c1-42ca-9bc0-837adb56d192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>7a40e5e6-d76b-4f88-9271-523e407b5a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/r/00TSu0000001ghxMAA/view</value>
      <webElementGuid>470b8114-f04d-42ea-b5ba-27b1221e8585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subjectLink slds-truncate</value>
      <webElementGuid>f92c25a8-a3ac-4f1a-8d80-ccecdb488f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>1c6afc32-bdc0-4770-bdb4-274b16fa520c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1132:0</value>
      <webElementGuid>9dd30249-1e47-4542-97f0-bb3de2a9ac55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tech Screen Scheduled: Demo19Automation19 TestContact19</value>
      <webElementGuid>f04ee30f-c73d-4e80-8fc8-03bc6ee04afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tech Screen Scheduled: Demo19Automation19 TestContact19</value>
      <webElementGuid>3be7b974-df0b-4a9e-9319-3150d742ecfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@class='subjectLink slds-truncate'])[1]</value>
      <webElementGuid>76e71e4d-28ed-4361-8830-aaf75824af0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upcoming-activities-section-003Su000001A0KkIAK']/div/ul/li/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/a</value>
      <webElementGuid>60b55c0c-3c75-462a-b114-1ebfe96c807c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tech Screen Scheduled: Demo19Automation19 TestContact19')]</value>
      <webElementGuid>348d3ab4-94bc-4a9f-a7d0-ccd32a7eb1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/00TSu0000001ghxMAA/view')]</value>
      <webElementGuid>31f62b3a-b51a-483d-82df-e4aa19b2d1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/a</value>
      <webElementGuid>4a157f52-b82b-4e77-a5cf-4cd55047e1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lightning/r/00TSu0000001ghxMAA/view' and @title = 'Tech Screen Scheduled: Demo19Automation19 TestContact19' and (text() = 'Tech Screen Scheduled: Demo19Automation19 TestContact19' or . = 'Tech Screen Scheduled: Demo19Automation19 TestContact19')]</value>
      <webElementGuid>389e2c97-8bd4-4f31-bd36-e55097177cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
