<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select an action</name>
   <tag></tag>
   <elementGuidId>259468e9-245b-4ff3-a5f0-7c0bc378622f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@class = 'slds-select']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1364:0']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f8f53c14-d242-4f03-972b-f3e701ae5569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea0400a7-f56e-4cbd-b5b6-4f2526c8f9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1364:0</value>
      <webElementGuid>b7c8954b-4c01-4ae0-a15f-9a2dbee98400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>fe57f3ae-cc07-484b-9b9f-685549cc5a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1375:0</value>
      <webElementGuid>cac6cad8-aba3-42b8-b1da-4b5733bfca8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assign TrainingContact Has Been MadeNo Longer ConsideringSend iMochaSchedule Tech ScreenSend Micro Course InvitesSend OfferSend RevaturePro InviteTransfer To Career CoachVerbal Commit</value>
      <webElementGuid>5407da32-9b71-4e57-8fff-f63edb2a9537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@class = 'slds-select']</value>
      <webElementGuid>1fb5137f-b946-4247-b049-630599b08f92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1364:0']</value>
      <webElementGuid>14344ff4-3421-4208-9682-acad77310ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div[3]/div/div/div/select</value>
      <webElementGuid>cbd4a9e7-ab17-426a-b8e3-867983253f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9f90701a-66b7-4540-8faf-5b80b3848338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '1364:0' and (text() = 'Assign TrainingContact Has Been MadeNo Longer ConsideringSend iMochaSchedule Tech ScreenSend Micro Course InvitesSend OfferSend RevaturePro InviteTransfer To Career CoachVerbal Commit' or . = 'Assign TrainingContact Has Been MadeNo Longer ConsideringSend iMochaSchedule Tech ScreenSend Micro Course InvitesSend OfferSend RevaturePro InviteTransfer To Career CoachVerbal Commit')]</value>
      <webElementGuid>0a5da5dc-9a91-4f20-8974-9f9d0b627b81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
