<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Corporate_slds-radio--faux</name>
   <tag></tag>
   <elementGuidId>197f68dd-0dd9-4f7e-b842-db7c00d58fd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='slds-radio--faux'])[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content_1149:0']/div/div/div/div/div/div/fieldset/div/div[5]/label/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(5) > label.slds-radio > div.changeRecordTypeOptionLeftColumn > span.slds-radio--faux</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2f0609b6-d83e-4088-bf53-0168b869a392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-radio--faux</value>
      <webElementGuid>127f0b58-8056-4f46-9c79-e7455d2d94ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1307:0</value>
      <webElementGuid>4e93a643-b1b5-4d2e-ab62-461337706d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='slds-radio--faux'])[3]</value>
      <webElementGuid>ebf691ae-e235-40ea-962e-1751b3b34206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_1149:0']/div/div/div/div/div/div/fieldset/div/div[5]/label/div/span</value>
      <webElementGuid>9dfd8ac8-b5b0-4fe9-80cb-c9a1ec7b172f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/div/span</value>
      <webElementGuid>0a4618ff-f048-451f-9d54-36d1b1e1bc71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
