<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accounting person</name>
   <tag></tag>
   <elementGuidId>763196ad-b992-440d-a129-53c970d82282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#strike-lookup-6106</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//input[contains(@class,'slds-lookup__search-input')])[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='strike-lookup-6106']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c2c172e-d852-4f38-9bbd-bc75e91e206d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>6f2154b7-1d87-4f6b-bea6-e673dfd07ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c546321d-842d-4e21-8ef1-96593574a027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cb0e1ce7-9846-48c9-beaa-bcd4aca1bfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53eb7d89-6b9a-4588-80b5-ae8b961f3d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-6106</value>
      <webElementGuid>04563826-fd79-41c6-8b0b-1089d0f22a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strike-lookup-6106</value>
      <webElementGuid>6d8db355-b8d3-40f0-89e7-9ede152eed3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__search-input slds-input js-template-lookup</value>
      <webElementGuid>c788fff9-18da-4b46-bd77-a3b4c4c70a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1224:0</value>
      <webElementGuid>8201c664-98ed-4a13-94d3-3294ceb69524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[contains(@class,'slds-lookup__search-input')])[4]</value>
      <webElementGuid>875f4db1-5252-4e5c-a77f-f705a5e5559e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='strike-lookup-6106']</value>
      <webElementGuid>08698fd3-c290-45e7-bbfc-529cf23dfec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-submittal_-record_-page___-submittal__c___-v-i-e-w/forcegenerated-flexipage_submittal_record_page_submittal__c__view_js/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[2]/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/div[2]/section/div/div/div/div[6]/div/div[2]/div/input</value>
      <webElementGuid>8a0c02d8-212f-4819-95d4-b1ec2e985ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>1a28e385-aac6-4bd5-8b16-0b86fa3ef6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input-6106' and @id = 'strike-lookup-6106']</value>
      <webElementGuid>1538c330-0da7-4db0-915d-215e338f8b08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
