<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bill Rate</name>
   <tag></tag>
   <elementGuidId>852576c7-9375-46b8-b30b-44cc65511591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-377</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//input[@class='slds-input'])[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-377']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6e63634-145d-488d-87d4-d5ece380c24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>da077c58-0458-43bd-a265-8717f5397723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-377</value>
      <webElementGuid>c7e69c1c-0fc6-428b-b79f-3ccba00c3a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-377</value>
      <webElementGuid>77d55d90-0c55-4270-b998-dfd60789778a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>a180c1a8-2658-4390-9bee-92e80f5dee3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5109930c-4c10-4899-a871-610130b05cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>35148ec1-e63f-4057-ad64-eda4fbcf5d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7dfa8f3e-7815-42f2-a12e-6ea18e27fc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@class='slds-input'])[2]</value>
      <webElementGuid>1c725a3f-33f9-47c1-8759-e74163a453c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-377']</value>
      <webElementGuid>e77a1479-fcf3-4715-b0e1-5381a0e867b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='995:0']/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>f92fd0bb-6fe7-47b8-8877-883f3050d69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>6bb39cc9-adcc-4e98-afca-e9020f4d9565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-377' and @type = 'text']</value>
      <webElementGuid>a1d6b41b-7e46-4f97-8530-816f2d0840e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
