<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Client reporting manager</name>
   <tag></tag>
   <elementGuidId>5ea7e2d6-803a-4062-8465-ccc0ce69656a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#strike-lookup-8790</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//input[contains(@class,'slds-lookup__search-input')])[5]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='strike-lookup-8790']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>833717f5-0efa-4bbf-ad53-df5438cbafd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>02047655-e099-4cdc-8f5a-a9bda5d1a02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>93a998b0-367c-4b5e-b99c-4dc62f89714d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>edb27357-df74-40fe-b24e-d92bf620f21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c6d2313-b800-4bb5-ad9e-1071c79311d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-8790</value>
      <webElementGuid>5ea47f24-073f-4e7d-9f42-1c522b155655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strike-lookup-8790</value>
      <webElementGuid>ad82e1a1-6321-4e41-8601-20a75881a67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__search-input slds-input js-template-lookup</value>
      <webElementGuid>e86b914d-fdb6-45ec-a9b4-60ccf2de7443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1270:0</value>
      <webElementGuid>2d057dc6-fa5b-480d-bea5-9711e29309d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[contains(@class,'slds-lookup__search-input')])[5]</value>
      <webElementGuid>20077d92-6691-40ec-ab02-54bd0f57599f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='strike-lookup-8790']</value>
      <webElementGuid>3391cc92-24e3-437f-9ba2-c854784e47a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-submittal_-record_-page___-submittal__c___-v-i-e-w/forcegenerated-flexipage_submittal_record_page_submittal__c__view_js/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[2]/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/div[2]/section/div/div/div/div[7]/div/div[2]/div/input</value>
      <webElementGuid>e3d4754c-e890-4dff-b4a9-148a8264af61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/input</value>
      <webElementGuid>af67801c-61d9-4724-9585-fd43ca08023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input-8790' and @id = 'strike-lookup-8790']</value>
      <webElementGuid>ade62265-20a7-4df3-b50b-0646ddcb7a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
