<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Remote_California</name>
   <tag></tag>
   <elementGuidId>b9244acc-928e-4630-b3fe-03e1578bd3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slds-lookup__menu > ul.slds-lookup__list > li > span.slds-lookup__item-action.slds-media > div.slds-media__body > div.slds-lookup__result-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[2]/div/div[4]/ul/li/span/div/div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='995:0']/div[2]/div[2]/div/div[4]/ul/li/span/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>246f3bd4-c398-4f6f-9146-5ff3faf430c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__result-text</value>
      <webElementGuid>025c4507-aebb-4b7c-8c81-9ddbecb79019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>7:1482;a</value>
      <webElementGuid>655cd4af-c4ee-460f-9969-c426ada2f375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remote_California</value>
      <webElementGuid>bb2da027-aac7-4c65-97f4-82aa4fbab3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/ul/li/span/div/div</value>
      <webElementGuid>f6d7098f-a2c8-4ec2-a051-ae83331aa915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='995:0']/div[2]/div[2]/div/div[4]/ul/li/span/div/div</value>
      <webElementGuid>cc90f60e-3420-4492-9e1f-94bc1f5e0c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/ul/li/span/div/div</value>
      <webElementGuid>8d9e321b-a1c0-4254-9cb5-abe854589fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Remote_California' or . = 'Remote_California')]</value>
      <webElementGuid>06c32984-c0ce-4e1f-a7b7-f3136b300a9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
