<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--None--9 months 1500 hrs12 months 2_c407a5</name>
   <tag></tag>
   <elementGuidId>ccf889b2-ce96-4890-b3c9-5947ebcec508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Conversion Term'])[1]/following::select[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1329:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2c97fdcf-f633-4a4c-99c2-49554e18b163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8bf0d0fa-068a-4346-87f0-fcec5690f97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1329:0</value>
      <webElementGuid>d94f87bc-21d6-430f-a027-53515fe5ef53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>e4c3d560-f47a-4270-8753-97402fff40ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1342:0</value>
      <webElementGuid>2c29eb88-7962-4e89-b59c-bc63faa81350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--None--9 months/ 1500 hrs12 months/ 2000 hrs15 months/ 2500 hrs18 months/ 3000 hrs18 months/ 3000 hrs full + 300 hrs reduced BRDirect hire</value>
      <webElementGuid>2f24d568-7b1a-4841-9c0f-fc1c155a9ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conversion Term'])[1]/following::select[1]</value>
      <webElementGuid>78dbc8a8-0187-46d5-9a3d-89f776e2b87e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1329:0']</value>
      <webElementGuid>8feb9ccf-58a2-4a11-b563-77c81226aa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-submittal_-record_-page___-submittal__c___-v-i-e-w/forcegenerated-flexipage_submittal_record_page_submittal__c__view_js/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[2]/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/div[2]/section/div/div/div/div[9]/div/div/select</value>
      <webElementGuid>e745f012-fd9e-46fb-a3d4-8b86def38a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conversion Term'])[1]/following::select[1]</value>
      <webElementGuid>be025710-1c83-42bd-b472-9daa8763f7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>c65f5f0a-f82e-4921-bedf-540202ce791d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[1]/preceding::select[1]</value>
      <webElementGuid>fe0c18bd-8b83-47b6-93f1-ecdac754a098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>0c648c93-9c79-4f5c-9165-bb02b2b0d312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/select</value>
      <webElementGuid>29cba811-df72-4d4c-831a-6ac170f56c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '1329:0' and (text() = '--None--9 months/ 1500 hrs12 months/ 2000 hrs15 months/ 2500 hrs18 months/ 3000 hrs18 months/ 3000 hrs full + 300 hrs reduced BRDirect hire' or . = '--None--9 months/ 1500 hrs12 months/ 2000 hrs15 months/ 2500 hrs18 months/ 3000 hrs18 months/ 3000 hrs full + 300 hrs reduced BRDirect hire')]</value>
      <webElementGuid>e015d2f6-8c7f-4c8d-803c-a9494a1b5b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
