<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Event</name>
   <tag></tag>
   <elementGuidId>cf5e78c1-c0df-403e-a4c0-023561b23eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @title = 'Create Event' and (text() = 'Create Event' or . = 'Create Event')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.icon-con > button.slds-button.slds-button_icon.slds-button_icon-border-filled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e5d4ea2-c059-45db-a55e-b639284a95e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>812a7aae-70a9-402f-978f-4d0f24c0d460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create Event</value>
      <webElementGuid>aafa4c56-5508-4b57-b7ba-0d0c36c1a59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_icon slds-button_icon-border-filled</value>
      <webElementGuid>b10c87df-366f-42c5-a3e1-798bec7a0d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>848:0</value>
      <webElementGuid>85f86f64-4bd6-49b0-9b0b-1117b2b17478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Event</value>
      <webElementGuid>2719e565-3bad-4cba-8dfc-caa11c2f9de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;screen-con cTechScreenAvailability&quot;]/div[@class=&quot;background&quot;]/div[@class=&quot;icon-con&quot;]/button[@class=&quot;slds-button slds-button_icon slds-button_icon-border-filled&quot;]</value>
      <webElementGuid>cf58d19a-7412-468b-adea-4ecabf2a5c76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>9f6cdbbf-5b1d-4f9d-9bc6-aa0cbdffae92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>15bf45f9-1182-4481-8778-1957e8a3445b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End of Feed'])[1]/following::button[1]</value>
      <webElementGuid>8d925062-b2b3-4578-9522-3b9362aab376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('It', &quot;'&quot;, 's all about you')])[1]/following::button[1]</value>
      <webElementGuid>0d583a9b-4d8a-47d1-a23f-1beb075cda02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All'])[1]/preceding::button[1]</value>
      <webElementGuid>cf8caf33-6026-48f8-8376-7dc7555e4835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>c5e169e6-60a4-4453-b040-b24ed92ff330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Create Event' and (text() = 'Create Event' or . = 'Create Event')]</value>
      <webElementGuid>829312d1-0540-450d-817b-2ff424df7fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
