<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>088ef0a9-d23e-4ea2-9f05-ae933ba2b92d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;oneHeader&quot;)/div[@class=&quot;slds-global-header slds-grid slds-grid--align-spread&quot;]/div[@class=&quot;slds-global-header__item slds-global-header__item--search&quot;]/div[@class=&quot;slds-grid slds-size_1-of-1 slds-grid--align-center forceSearchAssistant&quot;]/button[@class=&quot;slds-button slds-button_neutral search-button slds-truncate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_neutral.search-button.slds-truncate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a3aeb73-2b34-48a9-aa7e-5d9e36524c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e1090bf-c861-4075-ac7d-b88c8ecee7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_neutral search-button slds-truncate</value>
      <webElementGuid>8fc711b3-f4a8-45fa-ab64-d16aa896aa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>32b874cd-3c77-4c6f-96eb-9adbe23bbd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>115:0;p</value>
      <webElementGuid>913e0fd5-8962-4ed9-85a5-d5a3682a068b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>f4001fc4-f520-4939-ad39-deb3d4b3432b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneHeader&quot;)/div[@class=&quot;slds-global-header slds-grid slds-grid--align-spread&quot;]/div[@class=&quot;slds-global-header__item slds-global-header__item--search&quot;]/div[@class=&quot;slds-grid slds-size_1-of-1 slds-grid--align-center forceSearchAssistant&quot;]/button[@class=&quot;slds-button slds-button_neutral search-button slds-truncate&quot;]</value>
      <webElementGuid>7aff6683-2f69-46a3-91b5-a6d569d6a625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>f31d92d3-76f3-43af-a651-7c412b18c9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='oneHeader']/div[2]/div[2]/div/button</value>
      <webElementGuid>772588fe-a110-4982-86c8-5c0961349967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revature'])[1]/following::button[1]</value>
      <webElementGuid>14c981ea-a9a3-4e96-b16f-5b4f451a6180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::button[1]</value>
      <webElementGuid>66f7b33b-86e8-46da-ad9a-9c19eba03442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revature'])[2]/preceding::button[1]</value>
      <webElementGuid>9428d693-76c3-4164-afc7-cab2f456528a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('This item doesn', &quot;'&quot;, 't support favorites')])[1]/preceding::button[1]</value>
      <webElementGuid>6101b71c-3e61-4c41-a84d-4feda8031429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search...']/parent::*</value>
      <webElementGuid>ba6aef08-0a32-4d71-b7d1-01f8edf84a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4ed5abf0-1fc3-4e15-9e00-6a52b0e4d47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Search...' or . = 'Search...')]</value>
      <webElementGuid>4d55360f-2deb-4fc4-84eb-f4eaef431abe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
