<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date and Time_8850</name>
   <tag></tag>
   <elementGuidId>66de5e51-4047-4b3f-be20-f42c2c21299b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//fieldset/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='885:0']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9f14a26-ce2d-4b15-8780-998d05270299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>885:0</value>
      <webElementGuid>27e0dada-9d20-4150-a790-05fdf06d601c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e61d0102-e8f0-4e52-96e4-fcd83c2ab307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control slds-input input</value>
      <webElementGuid>a02fde27-2835-4dbc-8016-23df0229a5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>894:0</value>
      <webElementGuid>1759ef2a-c724-4a69-b021-9766d9a4d610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interactive-lib-uid</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3f3ce617-480f-4691-a306-9485907e4d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>31853ea6-56ba-4448-a351-0064c6c5a023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='885:0']</value>
      <webElementGuid>c4fc7b43-5c7c-41ec-984c-da796b94ea18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-content-id-1']/div[2]/div/fieldset/div/div/input</value>
      <webElementGuid>5a0b382b-c681-4c93-8621-7c142fefae10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>149ab508-f4ea-4d7f-ade8-60add9374234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '885:0' and @type = 'text']</value>
      <webElementGuid>be3d97e8-e982-48a2-a309-a3820393ad9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
