<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllStaging</name>
   <tag></tag>
   <elementGuidId>9927cd3c-ff26-4381-be36-906669f3bd53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='contact-header']/div[2]/div/div[2]/span/div/div/div/select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='898:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9e67b56-b540-49f2-8bac-f205263052e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3552da6-6cb3-4ddd-bd05-1c44c9ff0d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>898:0</value>
      <webElementGuid>4e32a26a-e22f-453d-8d99-2da3ae4ac685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>e682d158-7dcb-4ec9-ab50-b54ddc6908d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>916:0</value>
      <webElementGuid>500fda32-e3fb-4ae4-a0b3-64c12ac13421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Technology Filter</value>
      <webElementGuid>5bdb8cae-79b9-413f-898c-6cc094d716ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllStaging</value>
      <webElementGuid>df3a4e17-f644-4906-ba0c-31c86dc16083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div[2]/div/div[2]/span/div/div/div/select</value>
      <webElementGuid>27d33e35-2579-4024-88ee-ef9fc74ca953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='898:0']</value>
      <webElementGuid>2b29d01e-56b2-4ca6-8171-1114c55ced01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div[2]/div/div[2]/span/div/div/div/select</value>
      <webElementGuid>828d783a-e1b5-4307-8c72-b92c3e702df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/div/div/select</value>
      <webElementGuid>8b2924a1-2a4e-451f-a6a3-056711675214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '898:0' and @name = 'Technology Filter' and (text() = 'AllStaging' or . = 'AllStaging')]</value>
      <webElementGuid>3eb45ec3-76b4-4303-ab9a-8aeb1ed327bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
