<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terry Ahmed</name>
   <tag></tag>
   <elementGuidId>9123842e-547e-49a5-a047-9bdbbbd37f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='slds-media__body'])[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='1:5591;a']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1528aeb0-8ed7-4392-ac5b-e4cb9b9557ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Terry Ahmed</value>
      <webElementGuid>958b80cb-9cc5-4e64-bbca-e32b3605b2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryLabel slds-truncate slds-lookup__result-text</value>
      <webElementGuid>fc609334-cec7-4dbd-8285-1a25b56dacf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>10:5591;a</value>
      <webElementGuid>482391b0-42d4-4f95-8b81-58e928678d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terry Ahmed</value>
      <webElementGuid>818f54ed-5bfd-4c3f-8949-aa6644f6b80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='slds-media__body'])[4]</value>
      <webElementGuid>9add1c0e-b9f7-4044-8ac4-138ddee3e6b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='1:5591;a']/div[2]/div</value>
      <webElementGuid>2d19bb43-45f9-4dbb-9eb0-402f3f111fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T'])[6]/following::div[19]</value>
      <webElementGuid>7c106366-06fa-47c7-b4c5-8170e521c9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[5]/preceding::div[5]</value>
      <webElementGuid>bae76e40-7b6e-4d33-b8bc-ee0ce166d36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ahmed']/parent::*</value>
      <webElementGuid>2956e969-4565-4ae5-b039-b7f9d65360dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div[2]/ul/li[20]/a/div[2]/div</value>
      <webElementGuid>6b21e740-3ad1-4a27-bdad-29cacda6244d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Terry Ahmed' and (text() = 'Terry Ahmed' or . = 'Terry Ahmed')]</value>
      <webElementGuid>58e6237d-5e21-4606-a9a4-e27009823b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
