<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alexandra Gilroy</name>
   <tag></tag>
   <elementGuidId>a4d4f5b5-31c8-40dd-8c86-e3ae253be618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='slds-media__body'])[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='1:4927;a']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1cf37d62-0e96-4873-a71f-289d4c5a7425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Alexandra Gilroy</value>
      <webElementGuid>1383accc-6990-48d8-95be-c71e8e5957b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryLabel slds-truncate slds-lookup__result-text</value>
      <webElementGuid>795afdba-2aa0-4384-a84b-57171881a4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>10:4927;a</value>
      <webElementGuid>73dbb964-d94a-40c7-8fdd-56bb56437db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alexandra Gilroy</value>
      <webElementGuid>62d4bc30-a657-4418-9f05-0044ddbf5dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='slds-media__body'])[2]</value>
      <webElementGuid>2ad9946c-e089-4d72-8681-70f3757389f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='1:4927;a']/div[2]/div</value>
      <webElementGuid>7dadc05f-66d2-4fc0-aa1c-5dbaefb0b8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Recruiter'])[1]/following::div[35]</value>
      <webElementGuid>7860d9b8-a56d-4e99-9061-38cc3b7d09dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ale'])[1]/following::div[36]</value>
      <webElementGuid>a737da28-3f3e-46a9-86cb-9950b9a67fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Account Director'])[1]/preceding::div[1]</value>
      <webElementGuid>51c56e51-61f6-4821-afe6-1177c16013bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gilroy']/parent::*</value>
      <webElementGuid>7923edde-dac3-49a4-9e52-a8b796cfb683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[26]/a/div[2]/div</value>
      <webElementGuid>e735f923-7471-475b-8aee-5a88c6a3424a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Alexandra Gilroy' and (text() = 'Alexandra Gilroy' or . = 'Alexandra Gilroy')]</value>
      <webElementGuid>cc6b4560-0b69-4889-9dc4-5f7d9e5361a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
