<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MSA Expiration Date_MSAExpirationDate__c</name>
   <tag></tag>
   <elementGuidId>58a2a9f3-0b35-454a-9b24-3f975812a974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@type = 'text' and @name = 'MSAExpirationDate__c'])[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-568']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-568</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4644888d-69e2-4275-97b8-8b8b16e61651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>99e5f566-6d67-4114-8d1e-70baf30f8d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e49fc1e5-55f9-4a00-8088-14f0f5324e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-568</value>
      <webElementGuid>9ee60f05-9955-4b97-a4c7-960e1291da66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc45664a-5b69-40bf-9f8a-43c1cb3b64ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MSAExpirationDate__c</value>
      <webElementGuid>11e594ec-31d7-4540-89ad-137bd9d956eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>39c721f3-fe42-4fea-9b73-94a9424c7674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@type = 'text' and @name = 'MSAExpirationDate__c'])[2]</value>
      <webElementGuid>c4e72728-f4b1-4985-8ec4-613c0ed0c8a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-568']</value>
      <webElementGuid>3e8c3bf6-c115-44a0-9eb4-8f49057f7623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-220']/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>d4033fea-adf4-4783-b747-71c1e4e3217b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-component2[10]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/div/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>5ad5389d-7d04-461f-8bfd-f66a003a958c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-568' and @name = 'MSAExpirationDate__c']</value>
      <webElementGuid>892a1ee0-eef9-42dd-a57b-7070dfea6892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
