<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MSA Signed Date_MSA_Signed_Date__c</name>
   <tag></tag>
   <elementGuidId>7af3f157-ea00-4cc7-a449-0b123a974255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@type = 'text' and @name = 'MSA_Signed_Date__c'])[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-563']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-563</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>419ccd63-c8db-40d0-b5d5-3fd5bed34d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>83e06550-121c-4a23-a00f-444fd3dda939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27b178b0-f3ae-48f9-b971-08510d092b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-563</value>
      <webElementGuid>93221026-c692-4c61-9e1a-d95ab1b3c0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53232239-f9e7-40ac-a3a6-be16752e0456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MSA_Signed_Date__c</value>
      <webElementGuid>11be243f-6ef7-4583-bef0-dd09fc367191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>28e7ae27-836c-420d-9965-f890b55f9af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@type = 'text' and @name = 'MSA_Signed_Date__c'])[2]</value>
      <webElementGuid>75b4edff-31e9-42c1-b9c5-d26a9a9941b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-563']</value>
      <webElementGuid>218a3aad-5a71-48b0-ad5a-59a0f80082e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-220']/slot/flexipage-column2[2]/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>f5902ea2-1bd9-460c-a9a8-40bc59c2da5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-component2[10]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/div/slot/flexipage-column2[2]/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>bb15bf01-9ec8-4b42-aeb1-65f45daad1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-563' and @name = 'MSA_Signed_Date__c']</value>
      <webElementGuid>523b746a-fede-486a-a5a4-fea3619d4c3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
