<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-formatted-text_Auto_a138be</name>
   <tag></tag>
   <elementGuidId>4a14e534-6c5b-4cec-b584-e76a3c5f0056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-base-combobox-formatted-text.slds-truncate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//div[@role='listbox']/ul/li/lightning-base-combobox-item)[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-input-610-1-610']/span[2]/span/lightning-base-combobox-formatted-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-formatted-text</value>
      <webElementGuid>569d0cdc-df03-494e-a90c-4287a9317b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>8e867d7a-4c8e-4ae8-87a1-28c33409dba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AutoLead2contact4 testing4</value>
      <webElementGuid>b47e6cc7-3ccb-44b9-bf65-2973d83a1910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AutoLead2contact4 testing4</value>
      <webElementGuid>c60ba44d-b49b-4717-a085-fa44ac29b6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@role='listbox']/ul/li/lightning-base-combobox-item)[2]</value>
      <webElementGuid>ba079c20-2615-4c4e-a94f-556af90fb01c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-input-610-1-610']/span[2]/span/lightning-base-combobox-formatted-text</value>
      <webElementGuid>c84a5e03-5f7f-45dc-b7c3-50af5fc2a78b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-formatted-text</value>
      <webElementGuid>803d7da9-a8fd-4e26-afdd-c0420f68f9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-formatted-text[@title = 'AutoLead2contact4 testing4' and (text() = 'AutoLead2contact4 testing4' or . = 'AutoLead2contact4 testing4')]</value>
      <webElementGuid>0a76fb09-acac-4c0d-b813-6bd583610647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
