<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Signed</name>
   <tag></tag>
   <elementGuidId>ccf62923-6afc-4a6a-867c-f7fabe726545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Signed' or . = 'Signed')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-556-4-556']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-556-4-556 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf1579f3-88f8-4efb-bde0-b75ec65869f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>bad95f5b-0c2e-4813-bea6-2bc17c519904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Signed</value>
      <webElementGuid>e2c7a599-c9d6-4fa0-a378-f3d1367507c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-556-4-556&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>17fe3177-7512-4a3c-93f5-b60dfaeb6058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-556-4-556']/span[2]</value>
      <webElementGuid>480f6cb5-f903-4b34-a76b-8d09e84d689f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[5]/span[2]</value>
      <webElementGuid>d0563174-4696-4a7c-9536-3e1a66905896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Signed' or . = 'Signed')]</value>
      <webElementGuid>f9ba4332-b672-41ae-ab13-5f180dcec485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
