<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__RoomCapacity__c</name>
   <tag></tag>
   <elementGuidId>7e931bdb-463e-492f-ae4f-7ff5165d64aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'RoomCapacity__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//slot/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-882</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dd90630-a38c-47e8-81f0-a598f4e19733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>ec543525-1bb4-40a4-badd-7dafde50a8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e91c07b-a4ec-4ccb-a72f-d7b24e3e082a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-882</value>
      <webElementGuid>edc5fa6a-683f-49ba-a752-79aff2ff9062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>e5452c7d-44b1-4d1f-941e-51a4545998b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>0a4eb72a-0718-4db1-9497-52320f0357b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RoomCapacity__c</value>
      <webElementGuid>9f3b7d94-dfb4-4990-9a0a-5a0ce86441ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'RoomCapacity__c']</value>
      <webElementGuid>6734862b-ebc2-4e9b-87fe-70a467ea0015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-882']</value>
      <webElementGuid>55813810-0bd1-462d-ba77-0b6eeb35262e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-871']/div/slot/records-record-layout-row[2]/slot/records-record-layout-item[2]/div/span/slot/lightning-input/div/input</value>
      <webElementGuid>6415c395-55c8-433f-a4d6-2a190cc081eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//slot/lightning-input/div/input</value>
      <webElementGuid>e5be5a07-9032-4caa-8db9-e432fb359de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-882' and @name = 'RoomCapacity__c']</value>
      <webElementGuid>d9d1b9bd-73e7-457b-96d9-75749d162fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
