<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__RelocationAmount__c</name>
   <tag></tag>
   <elementGuidId>8914fe37-d801-49f0-809b-e5c23ec70d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'RelocationAmount__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//records-record-layout-row[4]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-234</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ade6e63d-db85-46b4-a9b2-a38692825cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>97958a6b-f208-463c-896e-a2c9d31774f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08e66aaa-6440-466c-903f-17d823517b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-234</value>
      <webElementGuid>778caaa5-a6f8-426d-ac52-0b68e12f6a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>7b760713-2b1a-4d5f-bd31-a962ba7c7b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>466a4c49-21ea-4527-9dea-db4da05be51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RelocationAmount__c</value>
      <webElementGuid>f90a9ce4-40a7-4009-9646-a14d3aa4d721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'RelocationAmount__c']</value>
      <webElementGuid>dedd0ab0-1c0b-49f6-97f0-c76859434ddc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-234']</value>
      <webElementGuid>06ada933-a571-4e28-a8f1-92f42efaa328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-208']/div/slot/records-record-layout-row[4]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>26b32a37-176b-4359-b600-c4abfdf45335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[4]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>64d8a8ed-1466-46e3-9d1a-6ce3d94228fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-234' and @name = 'RelocationAmount__c']</value>
      <webElementGuid>948cda4b-0cd0-43a1-b072-42946fa65ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
