<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_Active__c</name>
   <tag></tag>
   <elementGuidId>ceecc97c-1267-47ca-9df7-193ca57eaeab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'Active__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//records-record-layout-checkbox/lightning-input/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkbox-878</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9029c178-6fd3-4c09-a8b1-e1431db056b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a281b3a3-05af-4526-9e38-230378bade41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-878</value>
      <webElementGuid>eab364ea-7fc8-4bf3-a96a-a9f582a205c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Active__c</value>
      <webElementGuid>634a5097-f662-420c-bbde-1e49c0e8e44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@name = 'Active__c'])[2]</value>
      <webElementGuid>cd57f0d2-a336-471b-b666-43d9e0cc9e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-878']</value>
      <webElementGuid>0b96ac32-f870-4f58-ad40-b5a635f73b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-871']/div/slot/records-record-layout-row/slot/records-record-layout-item[2]/div/span/slot/records-record-layout-checkbox/lightning-input/div/span/input</value>
      <webElementGuid>28eaab94-87b9-4b36-932d-2f3dcd7ac6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-checkbox/lightning-input/div/span/input</value>
      <webElementGuid>f6504789-e2d7-4ee9-ab94-4e6136cd6296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox-878' and @name = 'Active__c']</value>
      <webElementGuid>a6940178-da53-42fa-a771-570cf0141b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
