<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ShippingLocation__c</name>
   <tag></tag>
   <elementGuidId>01222dc2-246e-46ad-9f23-9df5fa7ac267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'ShippingLocation__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//records-record-layout-section[2]/div/div/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-240</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d23ff48-1dd6-489b-a2b3-4f54bfbf83a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>f2f265c3-76fa-45ca-a868-d99a74176bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97ef838c-9e4e-4960-92fc-aec782950d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-240</value>
      <webElementGuid>9c898c15-e8e2-4f79-a78d-e6e2dfed25b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1be32092-4498-455c-9646-6d204e674074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ShippingLocation__c</value>
      <webElementGuid>c6b12583-472f-4d96-8c57-976bbd58cdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'ShippingLocation__c']</value>
      <webElementGuid>483a7a8d-093c-4f83-80c9-fce1b6ff3221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-240']</value>
      <webElementGuid>57ece5a8-d7a8-43db-8eae-e5cedef06182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-236']/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>060e7a4a-2fd3-4501-b88a-27a69e1487cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-section[2]/div/div/div/slot/records-record-layout-row/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>379eb52a-9887-4caf-8f15-5ca532b5c9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-240' and @name = 'ShippingLocation__c']</value>
      <webElementGuid>745065ef-47e1-4a4d-8a00-5cfb81e4939e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
