<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_UserKovardhani GDirector- HR Operations</name>
   <tag></tag>
   <elementGuidId>40d25f64-7393-4bf9-94c8-70fe5fe95b5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Show All Results for ', '&quot;', 'kov', '&quot;', '')])[1]/following::lightning-base-combobox-item[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Show All Results for ', '&quot;', 'kov', '&quot;', '')])[1]/following::lightning-base-combobox-item[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-296-1-296</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>28c36c95-7961-4011-b7d6-2228fffb03b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-listbox__option_entity slds-has-focus</value>
      <webElementGuid>3f2d7fa4-c896-4b9e-9c88-e42bd980f69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-input-296-1</value>
      <webElementGuid>e51875e9-bc69-405d-b3d7-5ae3015803e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0050d000006YUvEAAW</value>
      <webElementGuid>2767933a-280d-48ab-90d2-5bb2355e683d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cef96bc9-fdd1-42f2-9610-cc2773209f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-input-296-1-296</value>
      <webElementGuid>58dbaf80-cbae-41e5-9920-df65c49b1074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f7f7f5e-87d4-484d-b99a-e9c9c52c7902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e580b2e9-a801-4157-9949-aca2ae0bc6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UserKovardhani GDirector- HR Operations</value>
      <webElementGuid>bef476b1-cf79-4872-9b98-9e3798250491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Show All Results for ', '&quot;', 'kov', '&quot;', '')])[1]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>45748faa-50b6-4aa6-b5a2-c3a94f68a2dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-input-296-1-296']</value>
      <webElementGuid>694ed3aa-0bac-4b40-a9de-b9167d069ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-296']/ul/li/lightning-base-combobox-item</value>
      <webElementGuid>5029b40d-ea96-4ce9-b69c-4f54805c18f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Show All Results for ', '&quot;', 'kov', '&quot;', '')])[1]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>bd9e5dc6-a679-452a-afd0-ba58fbf88cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>5f244eb4-b1e5-424a-8702-f3a1e2c0516c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/lightning-base-combobox-item</value>
      <webElementGuid>7274f704-653c-464e-8545-6fa4e52da936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id = 'combobox-input-296-1-296' and (text() = 'UserKovardhani GDirector- HR Operations' or . = 'UserKovardhani GDirector- HR Operations')]</value>
      <webElementGuid>3fa54d64-21b4-4c6f-a62c-1a1168e9c96f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
