<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_External</name>
   <tag></tag>
   <elementGuidId>9aecf1f4-e489-4d02-9a7e-4e731c0c3811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Show All Results for ', '&quot;', 'external', '&quot;', '')])[1]/following::lightning-base-combobox-item[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[9]/following::strong[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-326-1-326 > span.slds-media__body > span.slds-listbox__option-text.slds-listbox__option-text_entity > lightning-base-combobox-formatted-text.slds-truncate > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>f6469091-ba7f-4f5b-81f2-91cb629b7299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>External</value>
      <webElementGuid>168fa24c-b4fd-4210-8fca-85e76198f96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Show All Results for ', '&quot;', 'external', '&quot;', '')])[1]/following::lightning-base-combobox-item[1]</value>
      <webElementGuid>02f842a3-5073-4c82-ba03-dbc4664fee11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-input-326-1-326']/span[2]/span/lightning-base-combobox-formatted-text/strong</value>
      <webElementGuid>8b95275c-e154-4de0-8bf0-e9e043f48c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[9]/following::strong[1]</value>
      <webElementGuid>6355cf2d-f6c8-48d7-899e-486d33788d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trainer'])[1]/preceding::strong[1]</value>
      <webElementGuid>80d69676-eab6-41ca-b69d-19f1298c4352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[10]/preceding::strong[1]</value>
      <webElementGuid>e7579701-97f7-48bc-9fe7-ddad9943a9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='External']/parent::*</value>
      <webElementGuid>923e3711-ca9c-4abb-9c4b-3cf4ad96ea63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[5]/slot/records-record-layout-item[2]/div/span/slot/records-record-layout-lookup/lightning-lookup/lightning-lookup-desktop/lightning-grouped-combobox/div/div/lightning-base-combobox/div/div[2]/ul/li/lightning-base-combobox-item/span[2]/span/lightning-base-combobox-formatted-text/strong</value>
      <webElementGuid>fdf30236-754a-4ca0-9586-05b8254aa31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'External' or . = 'External')]</value>
      <webElementGuid>d8d1db5c-a7be-4937-812c-ed8fbefe4df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
