<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Testing Opportunity21</name>
   <tag></tag>
   <elementGuidId>1a592551-5c11-46a9-9f90-195142a7b2cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.slds-lookup__menu > ul.slds-lookup__list > li > span.slds-lookup__item-action.slds-media > div.slds-media__body > div.slds-lookup__result-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//div[@class='slds-lookup__result-text'])[5]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div[3]/div/div[4]/ul/li/span/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>308a57a2-206b-4cee-98fc-5abe8afd7cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__result-text</value>
      <webElementGuid>87850242-0449-46f1-ad98-048b9d791065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>7:1106;a</value>
      <webElementGuid>c6577784-0b69-49b7-9935-cd29a9727872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing Opportunity21</value>
      <webElementGuid>0df10d0b-3947-49fe-a660-6473b9bc63ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@class='slds-lookup__result-text'])[5]</value>
      <webElementGuid>00ee1f89-70f1-4d69-8cc7-600e23823462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div[3]/div/div[4]/ul/li/span/div/div</value>
      <webElementGuid>63adf3dd-b802-437f-b511-741beb3d874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/span/div/div</value>
      <webElementGuid>4ab21e4d-5bfd-4b66-b003-1a855186a872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Testing Opportunity21' or . = 'Testing Opportunity21')]</value>
      <webElementGuid>0a35367b-b4f6-4b09-b1c7-6d0324b1922b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
