<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-2954</name>
   <tag></tag>
   <elementGuidId>53f50914-f026-407a-8500-0cd5bfd11d17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#strike-lookup-2954</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//*[@type = 'text'])[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='strike-lookup-2954']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b87b38d-f3a7-4858-9421-cdd7aaa6f6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>28af8db4-a1b0-45a7-9bea-5dce0de36e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5cd6a549-f825-4166-85d7-7c4c92ac2626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d419482-9130-4b04-8282-cc4053e9febb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9020385d-7e47-4b2a-b6ff-04025f640767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-2954</value>
      <webElementGuid>f2081c42-3747-4e42-b67f-dd8db5d09c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strike-lookup-2954</value>
      <webElementGuid>1b2574ca-952d-4ea8-93ee-d14c4832773b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__search-input slds-input js-template-lookup</value>
      <webElementGuid>3f799ff6-f0d1-4200-8899-32d42f0cc76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1118:0</value>
      <webElementGuid>6b877d63-e9a8-4a51-b260-05fe1883ef11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@type = 'text'])[2]</value>
      <webElementGuid>40367ff8-5e7f-42aa-8aeb-7ebd66476ff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='strike-lookup-2954']</value>
      <webElementGuid>d73264df-6f45-43fb-88a2-83180ed5164e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div[3]/div/div[2]/div/input</value>
      <webElementGuid>c25ebf25-3be8-4b40-a2d1-8c72aae66dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>9a6494b5-c396-4b10-927f-51ba5dd4a1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input-2954' and @id = 'strike-lookup-2954']</value>
      <webElementGuid>d41af497-c9f9-4599-9ec2-3ee5745e4f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
