<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Internal</name>
   <tag></tag>
   <elementGuidId>6e29a866-5e3f-4534-931d-401695a61764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-24 > slot > flexipage-component2 > slot > lst-dynamic-related-list > article.slds-card.slds-card_boundary > laf-progressive-container > slot > lst-dynamic-related-list-with-user-prefs > lst-related-list-view-manager > lst-common-list-internal > div.slds-grid.listDisplays > div.slds-grid.slds-border__left.slds-border__right.listViewContainer > lst-primary-display-manager > div.slds-col.slds-no-space.display-wrapper > lst-primary-display > lst-primary-display-grid > lst-customized-datatable > div.dt-outer-container > div.slds-table_header-fixed_container.slds-scrollable_x > div.slds-scrollable_y > table.slds-table.slds-table_header-fixed.slds-table_bordered.slds-table_edit.slds-table_resizable-cols > tbody > tr.slds-hint-parent > td:nth-of-type(2) > lightning-primitive-cell-factory > span.slds-grid.slds-grid_align-spread</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@title='Internal']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//flexipage-tab2[@id='tab-24']/slot/flexipage-component2/slot/lst-dynamic-related-list/article/laf-progressive-container/slot/lst-dynamic-related-list-with-user-prefs/lst-related-list-view-manager/lst-common-list-internal/div/div/lst-primary-display-manager/div/lst-primary-display/lst-primary-display-grid/lst-customized-datatable/div[2]/div/div/table/tbody/tr/td[2]/lightning-primitive-cell-factory/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be0550db-e59d-44e3-b779-979e7092a9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-grid slds-grid_align-spread</value>
      <webElementGuid>863ede60-c2cf-4fab-915c-65684c23db25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Internal</value>
      <webElementGuid>88c70c1d-6fa6-4319-9966-0d4c7017d096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@title='Internal']</value>
      <webElementGuid>9e9565d2-f0ac-4e7c-9a12-ac9396a04180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flexipage-tab2[@id='tab-24']/slot/flexipage-component2/slot/lst-dynamic-related-list/article/laf-progressive-container/slot/lst-dynamic-related-list-with-user-prefs/lst-related-list-view-manager/lst-common-list-internal/div/div/lst-primary-display-manager/div/lst-primary-display/lst-primary-display-grid/lst-customized-datatable/div[2]/div/div/table/tbody/tr/td[2]/lightning-primitive-cell-factory/span</value>
      <webElementGuid>c96bc84d-6a03-47e3-83a9-de653fe9967a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-tab2[4]/slot/flexipage-component2/slot/lst-dynamic-related-list/article/laf-progressive-container/slot/lst-dynamic-related-list-with-user-prefs/lst-related-list-view-manager/lst-common-list-internal/div/div/lst-primary-display-manager/div/lst-primary-display/lst-primary-display-grid/lst-customized-datatable/div[2]/div/div/table/tbody/tr/td[2]/lightning-primitive-cell-factory/span</value>
      <webElementGuid>13d27f26-9054-466a-9fbe-1ca5c1d5ecad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Internal' or . = 'Internal')]</value>
      <webElementGuid>3fcf4e61-7f8d-433a-9eaa-9f8c8bfa9239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
