<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Basics Score_scoreInput</name>
   <tag></tag>
   <elementGuidId>271c1c1c-4493-4387-b8be-a0bf726bea85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@class = 'slds-input' and @name = 'scoreInput'])[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[2]/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-1015</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>866e5516-0f8d-43a4-a85d-275b4241f7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>1d45d48b-55ee-48a4-a7ac-a3ecd2959a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c78ce7dd-5b05-424a-8dbe-6c07e6b82cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1015</value>
      <webElementGuid>82156cb8-07a6-42e7-89ac-7fc8e620a1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a7403a24-1f2b-4ec5-b7d7-a01fe236a737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb1ef202-85a8-4d3e-9322-e94e10d6f92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>bf3c3cf3-c420-4984-b5dc-0c142ce7a468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scoreInput</value>
      <webElementGuid>4d97cbfd-c203-4864-969b-12241baceb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@class = 'slds-input' and @name = 'scoreInput'])[2]</value>
      <webElementGuid>ec241b08-629a-4886-a668-bda58648ec3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1015']</value>
      <webElementGuid>0406af5e-b17b-4121-b3b1-b392f162b6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[2]/lightning-input/div/input</value>
      <webElementGuid>fb3ad12a-83ee-487b-9d92-a62f8810207d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/div/input</value>
      <webElementGuid>0186c0cd-4751-4b2e-9669-d46ea5684b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-1015' and @name = 'scoreInput']</value>
      <webElementGuid>aba7508d-6473-4153-88c0-9e3e6ac79a08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
