<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Advanced Score_scoreInput</name>
   <tag></tag>
   <elementGuidId>903d29bc-bc56-491e-9e71-04450878f7f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@class = 'slds-input' and @name = 'scoreInput'])[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[3]/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-1016</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb45071e-f4c5-4ca0-b051-f36686d2787a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>8d28e2bd-76b1-4c62-af3c-227f9af3029f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>125b34bc-4f71-42f2-925e-aba9e1be3d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1016</value>
      <webElementGuid>79bfcaad-6e1b-463c-bf44-db9ec5862114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>00336dbb-c8f5-4804-9d52-b59a2318e957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1948d6db-a775-4843-9bf1-3328de72c2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>d88e8158-552b-4996-991b-e56974e43117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scoreInput</value>
      <webElementGuid>6945a247-9b5e-4d3f-9d78-5c9c19290691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@class = 'slds-input' and @name = 'scoreInput'])[3]</value>
      <webElementGuid>3821d49b-4806-4a07-ab4f-3384b3519add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1016']</value>
      <webElementGuid>4e492ecf-8647-49f5-bc28-a844cec00518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[3]/lightning-input/div/input</value>
      <webElementGuid>8d312bc1-ce19-43d2-9554-7b05cc1b7648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/lightning-input/div/input</value>
      <webElementGuid>b3f5dc9e-6a97-4482-975e-bda70f972161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-1016' and @name = 'scoreInput']</value>
      <webElementGuid>7b908eb1-d3e3-4678-836d-591b9e535bb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
