<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Web Score_scoreInput</name>
   <tag></tag>
   <elementGuidId>996701a6-68e3-45dd-a7e2-26942286fd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@class = 'slds-input' and @name = 'scoreInput'])[5]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[5]/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-1018</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d52ce93-9540-44e0-ae6b-2d7a50381b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>8ae7c7be-2dce-4dd4-94b3-7c7067d77e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1daa1a7-b15d-4fc6-ad1e-488247f7d433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1018</value>
      <webElementGuid>0794e033-c87a-48be-a277-b8ae5c0a1ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>5cf1b594-4583-4880-99f8-9f7c48b40c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ed4bd87-96a2-480a-b49f-3d2fb0d83151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>7d6b5634-713b-41a7-b9b7-91b74c4af7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scoreInput</value>
      <webElementGuid>7774350e-7cfb-4dad-9390-4a2fde5acf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@class = 'slds-input' and @name = 'scoreInput'])[5]</value>
      <webElementGuid>7a46a72d-ed1c-4189-986d-a06296472ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1018']</value>
      <webElementGuid>35994b4d-5875-4f64-a1b2-b502b702fbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[5]/lightning-input/div/input</value>
      <webElementGuid>bcf191e6-ba93-4d80-abc9-90ebce8e6008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/lightning-input/div/input</value>
      <webElementGuid>99598d5a-206b-424f-a5b6-f693f6e0b242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-1018' and @name = 'scoreInput']</value>
      <webElementGuid>b7ab4acb-29fe-4f91-b683-6e6509175d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
