<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes</name>
   <tag></tag>
   <elementGuidId>bcbd8736-73db-4b79-83a6-94e64c3d1805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div[2]/lightning-radio-group/fieldset/div/div/span/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slds-radio_faux</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5ee32b42-8ea7-44b6-a754-5a1c4281f82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-radio_faux</value>
      <webElementGuid>95192a56-126a-41f5-8ff2-b648dec820e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>ea27fd98-d148-4811-8615-74e1276e1ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-header&quot;)/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-no-flex slds-grid slds-align-top&quot;]/div[@class=&quot;cProcessButton&quot;]/section[@class=&quot;slds-modal slds-modal_large slds-fade-in-open&quot;]/div[@class=&quot;slds-modal__container&quot;]/div[@class=&quot;slds-modal__content slds-p-around_medium&quot;]/div[@class=&quot;slds-grid slds-p-around_x-small cEnterScreeningScore&quot;]/div[@class=&quot;slds-col slds-size_2-of-12&quot;]/lightning-radio-group[@class=&quot;slds-form-element&quot;]/fieldset[1]/div[@class=&quot;slds-form-element__control&quot;]/div[@class=&quot;slds-radio_button-group&quot;]/span[@class=&quot;slds-button slds-radio_button&quot;]/label[@class=&quot;slds-radio_button__label&quot;]/span[@class=&quot;slds-radio_faux&quot;]</value>
      <webElementGuid>047b6aaf-ad1a-4e83-b85e-635f1f41199f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div[2]/lightning-radio-group/fieldset/div/div/span/label/span</value>
      <webElementGuid>1f57e6d9-7384-4744-bdd9-d4317506f006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acceptable Soft Skills?'])[1]/following::span[2]</value>
      <webElementGuid>6ce6dbbc-8300-48ad-ba8d-479af073adcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular'])[1]/following::span[2]</value>
      <webElementGuid>e62b2f41-ad47-48f9-aaab-345846cda624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::span[1]</value>
      <webElementGuid>05ae10e0-9dc0-4622-91df-9de07cdd5169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Final Score'])[1]/preceding::span[3]</value>
      <webElementGuid>dfd51973-fcf2-4180-872f-97a7c813e6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>0bcda902-2d4c-4918-9c6f-e12b7d332c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/label/span</value>
      <webElementGuid>c0b67e20-9988-4e58-8557-16a12eb2b082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>1cd34f16-c406-4e5a-b23c-67ee0a6ace1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
