<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>External record type ratio button</name>
   <tag></tag>
   <elementGuidId>1c181f91-4585-43d0-b305-b80cd1ebb171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='slds-radio--faux'])[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content_1657:0']/div/div/div/div/div/div/fieldset/div/div[7]/label/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(7) > label.slds-radio > div.changeRecordTypeOptionLeftColumn > span.slds-radio--faux</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ea7de38-d938-4824-8b40-f3e19a4b377b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-radio--faux</value>
      <webElementGuid>201e694a-4ede-4fa1-9049-bc12bdb126d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1833:0</value>
      <webElementGuid>eec5bdc1-8604-477a-873a-30c5920e3232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='slds-radio--faux'])[3]</value>
      <webElementGuid>ea4f4a62-cee2-4502-8625-225d01538129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_1657:0']/div/div/div/div/div/div/fieldset/div/div[7]/label/div/span</value>
      <webElementGuid>c2f6d7bc-a1b8-4264-a2cd-ad81ecea086e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label/div/span</value>
      <webElementGuid>0dd9957e-620b-473d-933d-49487f195163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
