<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_province</name>
   <tag></tag>
   <elementGuidId>3392a873-26b2-402c-a595-44b15530d176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @name = 'province']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combobox-input-459']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-459</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b06324e3-bc5d-4549-8398-721a69c4d5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-combobox__input slds-input slds-combobox__input-value</value>
      <webElementGuid>89eb5039-13e6-4643-9358-28ab5ca58c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-input-459</value>
      <webElementGuid>5d124fb9-0fc8-4c4e-8129-a48d0d949d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a16d1841-708b-48e3-8fd1-7a10e0f8312a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>cef8b59a-f5ec-430f-8e8c-f34f1bb5ad5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a0be11a-3597-4bd1-9b2b-8ebbcb053c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>de7d33cd-86df-4ffc-9685-5a497c01f66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-level1</value>
      <webElementGuid>ccc673ad-ce29-4fc3-8ad8-2cae78b674fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>--None--</value>
      <webElementGuid>63a894fb-f18c-453d-a2f4-62981f16801a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>5e56cd5d-3661-411d-99a2-824a26811fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f173b187-b0f2-45d1-941e-b552c6e8e131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>17579603-313b-462e-a919-54942d9b100e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>dropdown-element-459</value>
      <webElementGuid>a3a5b7ce-9e90-4d97-b952-14d47ad79487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Mailing State/Province</value>
      <webElementGuid>18ec95a2-6ba9-4602-a829-5a23e657ccc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f78631dc-d2c5-4656-b4a3-4d6bc9db9643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-element-459</value>
      <webElementGuid>c12e7735-aa1e-4d02-a506-5fc882a17315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'province']</value>
      <webElementGuid>5075de72-53ad-4fd7-a0e0-4da5befc80bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combobox-input-459']</value>
      <webElementGuid>79175ef0-68f3-40af-a9ba-39f36ee3f67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-427']/div/slot/records-record-layout-row[3]/slot/records-record-layout-item/div/span/slot/records-record-layout-input-address/lightning-input-address/fieldset/div/div/div[4]/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div/div/div/input</value>
      <webElementGuid>6308926e-8fc2-47e1-aab2-f2d5edc2472b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div/div/div/input</value>
      <webElementGuid>380fbc0f-357f-4866-ba3e-597783d59bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combobox-input-459' and @type = 'text' and @name = 'province']</value>
      <webElementGuid>5c6c8810-d878-438c-8e5a-e1a39068f715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
