<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputcombobox-input-540</name>
   <tag></tag>
   <elementGuidId>02387eb7-43cc-48d5-a4c9-276e2894791f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='combobox-input-540']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-540</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b4b63db-e72b-4bf3-94f8-7f0bb2bc25d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-combobox__input slds-input</value>
      <webElementGuid>e4bf4f5d-c3a8-4b6b-85f3-978606d451f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-input-540</value>
      <webElementGuid>7701f6a9-bacd-4a05-98bb-a79ffe58dc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c4e525a-e272-487e-a63b-5063de9435a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f752e770-37e9-4959-b212-66094834b21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3cd440d3-5f20-46e9-8ba3-448db1ab3b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>4d1bb369-db9f-4473-b49e-ef8bfe757be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>62b18e2d-6116-4357-9770-39e710d1a56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Address</value>
      <webElementGuid>4d07a559-c2f4-492d-b0d7-71e3abcd862c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>1b05b031-9683-4cbc-a854-826002e4b98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>dropdown-element-540</value>
      <webElementGuid>eff02385-9c9a-43e9-8882-29a8b868bc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ac8b26a-a3bf-403b-abe5-0b6ab659b293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-element-540</value>
      <webElementGuid>fad85025-954a-4769-9af2-b1cacc5da4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-input-540&quot;)</value>
      <webElementGuid>6eedc9c8-716c-48b0-a2eb-442af990056e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='combobox-input-540']</value>
      <webElementGuid>291ef6ff-ed09-40f0-bac4-a53ed9c826f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-427']/div/slot/records-record-layout-row[3]/slot/records-record-layout-item/div/span/slot/records-record-layout-input-address/lightning-input-address/fieldset/div/div/div/lightning-lookup-address/div/lightning-base-combobox/div/div/div/div/div/input</value>
      <webElementGuid>cd7a4cca-54f9-4681-9210-1b67e0288723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-lookup-address/div/lightning-base-combobox/div/div/div/div/div/input</value>
      <webElementGuid>c5e65c97-39de-4382-bf43-96101d1b03f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'combobox-input-540' and @type = 'text' and @placeholder = 'Search Address']</value>
      <webElementGuid>166ddbe3-0c18-40a0-82aa-cfb7f0357a66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
