<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bank_Name__c</name>
   <tag></tag>
   <elementGuidId>fb70c5a0-db5e-46e3-9d6c-bbd6026e4c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'Bank_Name__c' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-390']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-390</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f63c846e-357e-4d8e-ad5b-9925a5552eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>4f157aa0-a02d-495e-870a-a7d42585ad92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-390</value>
      <webElementGuid>009e2bd4-3968-4b7b-ac47-95fe0f33f427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-390</value>
      <webElementGuid>fe205658-c3a4-4eec-9214-1c1ffac8b760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f8eb7cf9-6bbd-43fb-a285-c0cc64bcc41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bank_Name__c</value>
      <webElementGuid>992c1bdc-fd94-43e9-8870-9426c65021dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01633deb-39ab-4104-8fa3-954aa057b0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cda3f16-9cca-4ff2-8db6-5fe3c17c4a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name = 'Bank_Name__c' and @type = 'text']</value>
      <webElementGuid>55656fc8-553c-45c5-b6c7-47a3676164ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-390']</value>
      <webElementGuid>4d32790d-d832-478f-adad-742b9aa8f7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-378']/div/slot/records-record-layout-row/slot/records-record-layout-item[2]/div/span/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>948dae04-2d6a-4980-b5d2-f87e7a190db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-section[3]/div/div/div/slot/records-record-layout-row/slot/records-record-layout-item[2]/div/span/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>17b1a7ff-795c-4735-8cc7-5195b6b26403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-390' and @name = 'Bank_Name__c' and @type = 'text']</value>
      <webElementGuid>ef10570e-5d4b-4a10-8bc6-f6387416b17e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
