<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mailing_street</name>
   <tag></tag>
   <elementGuidId>4ee9dfb8-2a95-4bce-8c28-eeae52914785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@name='street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@name='street']</value>
      <webElementGuid>9a98eb9a-2602-43bc-98e7-fdb9ab62b188</webElementGuid>
   </webElementProperties>
</WebElementEntity>
