<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ETK</name>
   <tag></tag>
   <elementGuidId>2cfe625d-8fb7-4ce5-bb43-25031de22f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-361-1-361']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-361-1-361 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d0edd22-d3d9-4339-8c11-36b7202c8b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>f8c739a1-df10-48a3-a10e-3bc4af94edd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ETK</value>
      <webElementGuid>6d2c4d63-40d8-45bd-8b60-e05c9c79eaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-361-1-361&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>c37f3362-161d-44f3-bab6-9cb9d0e1c757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-361-1-361']/span[2]</value>
      <webElementGuid>a2995ea1-cdf9-4149-b5d5-8d2e561cdf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[4]/slot/records-record-layout-item[2]/div/span/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[2]/span[2]</value>
      <webElementGuid>47680d6d-ee71-4908-a71a-5abd8d39fcdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ETK' or . = 'ETK')]</value>
      <webElementGuid>f3c4967c-e18c-4271-b4e1-f58a1a988ed7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
