<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PO-0028</name>
   <tag></tag>
   <elementGuidId>dc66be50-5ca5-4dad-aba3-bc58aac99f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='window']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#window</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(text(),'PO')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49f12079-da8e-4532-958c-46845b14aab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-wrap-ie11 slds-truncate</value>
      <webElementGuid>5cabe188-2865-4163-9c3a-f55300deac73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/r/a1IOt000000b9xBMAQ/view</value>
      <webElementGuid>6bc4c37e-aa0b-4486-8cc3-000469d66bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ccdfcc44-7262-461e-8412-c0baa8f42b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-proxy-id</name>
      <type>Main</type>
      <value>aura-pos-lib-8</value>
      <webElementGuid>2e121f29-9124-475d-a13b-8ddc899c80a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>window</value>
      <webElementGuid>e4c391a9-ef36-4732-b6d4-ac263148b927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PO-0028</value>
      <webElementGuid>80df8865-2665-49b3-9fc8-9fb2159336f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(text(),'PO')])[3]</value>
      <webElementGuid>788fcfd9-dda1-4793-8719-0c70556349f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='window']</value>
      <webElementGuid>7842bfec-8ab2-4717-b094-e89d01ba9f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flexipage-tab2[@id='tab-2']/slot/flexipage-component2/slot/lst-related-list-single-container/laf-progressive-container/slot/lst-related-list-single-app-builder-mapper/article/lst-related-list-view-manager/lst-common-list-internal/div/div/lst-primary-display-manager/div/lst-primary-display/lst-primary-display-grid/lst-primary-display-grid-shim/lst-bundle_act_core-related-list-desktop_datatable/div[2]/div/div/table/tbody/tr/th/lightning-primitive-cell-factory/span/div/lightning-primitive-custom-cell/lst-output-lookup/force-lookup/div/records-hoverable-link/div/a</value>
      <webElementGuid>a1b48180-9dd3-461f-b634-9967bee0f74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/a1IOt000000b9xBMAQ/view')]</value>
      <webElementGuid>69c28056-725e-443b-ba82-398c7911e6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lst-output-lookup/force-lookup/div/records-hoverable-link/div/a</value>
      <webElementGuid>561d5522-b3df-4cf9-98e4-731f4a2be305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lightning/r/a1IOt000000b9xBMAQ/view' and @id = 'window' and (text() = 'PO-0028' or . = 'PO-0028')]</value>
      <webElementGuid>14fb3b6c-985b-48ad-9e7d-5a7be6e27adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
