<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New</name>
   <tag></tag>
   <elementGuidId>e6529a9f-6d71-4b74-996c-849338567c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='New']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;New&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@name = 'New' and @type = 'button' and (text() = 'New' or . = 'New')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4189bb11-3ed6-4387-96c4-9cd18b56c236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_neutral</value>
      <webElementGuid>56aecfaf-3516-4310-ba9b-d6f98ae5e98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ebb23f85-de2b-4073-9454-e982a975386f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>74f6a290-a876-4013-982e-d6d156fbacb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8ea205e-6b34-4015-8596-c1d361d80fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6efbbff4-0455-45a1-bdc2-763dc155fd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kx-scope</name>
      <type>Main</type>
      <value>button-neutral</value>
      <webElementGuid>f25ec8fd-dc86-4851-8d29-1ce7bc26b2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kx-type</name>
      <type>Main</type>
      <value>ripple</value>
      <webElementGuid>a7e67819-3253-442e-829c-c2ce7127bf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>c3b3a8b8-5949-4fc0-a4cd-6fd29f9857f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@name = 'New' and @type = 'button' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>1612e5ca-c7dc-4a06-ba66-0aa75c5271ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='New']</value>
      <webElementGuid>cfca41d0-f345-4573-8a3e-0ecf53d8de63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flexipage-tab2[@id='tab-2']/slot/flexipage-component2/slot/lst-related-list-single-container/laf-progressive-container/slot/lst-related-list-single-app-builder-mapper/article/lst-related-list-view-manager/lst-common-list-internal/lst-list-view-manager-header/div/div/div[3]/div/runtime_platform_actions-actions-ribbon/ul/li/runtime_platform_actions-action-renderer/runtime_platform_actions-executor-delayed-aura-legacy/slot/slot/lightning-button/button</value>
      <webElementGuid>48085304-61c3-4a00-a47d-6af5edc8a7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lst-list-view-manager-header/div/div/div[3]/div/runtime_platform_actions-actions-ribbon/ul/li/runtime_platform_actions-action-renderer/runtime_platform_actions-executor-delayed-aura-legacy/slot/slot/lightning-button/button</value>
      <webElementGuid>3b477229-4a66-4a58-bc99-53bccbbd0681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'New' and @type = 'button' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>e4b9522c-49a9-47f3-93a0-10f6d200d278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
