<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill_Rate__c</name>
   <tag></tag>
   <elementGuidId>6000117c-c0d5-4539-b30b-391aa9193789</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-553']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-553</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'Bill_Rate__c' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d67e31f-1cea-4501-b545-871e4c5543d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>84e26a7f-6f37-4d73-9086-76d28f90b688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-553</value>
      <webElementGuid>0cead280-e42e-4e0e-af3b-199d1265836c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-553</value>
      <webElementGuid>5d6c1fab-8c12-4fb9-893f-12c213432af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>6f5ffffe-b5db-4bab-af03-4076a1631731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Bill_Rate__c</value>
      <webElementGuid>033e8559-fb7d-4042-aaf2-52b42beab748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a11d5b26-c51d-4c61-afa7-16580ba9f5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>66155fd3-3c71-42ff-9415-1faf152e6c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c03853a3-5867-4545-b9c9-0381abff7bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name = 'Bill_Rate__c' and @type = 'text']</value>
      <webElementGuid>b0b1b869-b79f-4b61-bc9e-a28cd3edce44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-553']</value>
      <webElementGuid>2bff3c61-fba8-44f9-974c-184291e5f6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-524']/div/slot/records-record-layout-row[4]/slot/records-record-layout-item/div/span/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>9c26701e-f7f8-4b33-af18-5c2a15826d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>62f0ebdc-d8f0-461b-835d-6705c1f9eaa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-553' and @name = 'Bill_Rate__c' and @type = 'text']</value>
      <webElementGuid>3fdefae6-8ba8-4bdc-8c62-406f4488afd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
