<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start_Date__c</name>
   <tag></tag>
   <elementGuidId>e5bb824a-aa4f-47a8-8cdc-f85db9669eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-568']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-568</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @name = 'Start_Date__c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f33cf68-f2e2-49fe-84f7-adc524b0c166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>cd872130-5c50-4239-8269-ed780228a0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>030b593b-3e94-4823-b0db-726f5d6d4174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-568</value>
      <webElementGuid>32703ccc-70af-427b-84d5-0769f4dccbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b25a4fd8-e297-40b1-acdc-5045b9c3c793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Start_Date__c</value>
      <webElementGuid>66fcdd93-77a7-4ae4-83d2-e2ce1fa53fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c568436b-9134-45ca-8b3d-6bd9862955a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Start_Date__c']</value>
      <webElementGuid>0bdc5690-5d34-4855-a717-ffe5f9828862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-568']</value>
      <webElementGuid>c62ab1b7-c7b4-414d-9e3c-e67a87c1a649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-524']/div/slot/records-record-layout-row[6]/slot/records-record-layout-item/div/span/slot/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>828310bb-275e-4bc2-a7c7-8c7549a6e0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>1a7756c9-cb6c-49f9-89f6-c05fc28420b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-568' and @name = 'Start_Date__c']</value>
      <webElementGuid>788d7dde-dbba-4ea7-8205-9f6946d27f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
