<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Core java katalon13</name>
   <tag></tag>
   <elementGuidId>dda7e7d7-f95c-4cf5-ae1d-83ed58250633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-input-607-1-607']/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-607-1-607 > span.slds-media__body > span.slds-listbox__option-text.slds-listbox__option-text_entity</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(@class,'slds-listbox__option-text')]//lightning-base-combobox-formatted-text)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3086af7-5416-4ea6-88ea-80e3c96e8225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-listbox__option-text slds-listbox__option-text_entity</value>
      <webElementGuid>4884fc1d-3ee8-4a17-9e85-f905def31b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Core java katalon13</value>
      <webElementGuid>c9aac1d9-1d04-4eb5-9518-b856a260d1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(@class,'slds-listbox__option-text')]//lightning-base-combobox-formatted-text)[1]</value>
      <webElementGuid>d424276a-cc36-4767-b5f0-48b2331a9831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-input-607-1-607']/span[2]/span</value>
      <webElementGuid>a080150b-1487-4174-98e4-84ba9ebd3465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/lightning-base-combobox-item/span[2]/span</value>
      <webElementGuid>5e379232-af0f-4e52-bba8-71253b6a434c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Core java katalon13' or . = 'Core java katalon13')]</value>
      <webElementGuid>5835d6c0-0e3f-4bf2-b7a7-2d9bcff0a07c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
