<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TRNG-00001841</name>
   <tag></tag>
   <elementGuidId>c0da9bbf-3d54-4d1e-83b4-c7bed1ea2c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-input-601-1-601']/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-601-1-601 > span.slds-media__body > span.slds-listbox__option-text.slds-listbox__option-text_entity</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//strong[contains(text(),'TRNG')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>71ed8560-4e2f-48e6-9352-144ada30ace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-listbox__option-text slds-listbox__option-text_entity</value>
      <webElementGuid>02b1a9ea-d040-4d92-9d52-aca00a8f4e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRNG-00001841</value>
      <webElementGuid>2e3ebb47-49bd-4b53-a791-d76a02873629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[contains(text(),'TRNG')]</value>
      <webElementGuid>e4d77c50-4846-4cf2-a690-70370026a327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-input-601-1-601']/span[2]/span</value>
      <webElementGuid>76807960-f75b-4116-b74b-5b6198130d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/lightning-base-combobox-item/span[2]/span</value>
      <webElementGuid>6627a70f-6ee8-4d21-902f-4263f2e37cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TRNG-00001841' or . = 'TRNG-00001841')]</value>
      <webElementGuid>2d9dc779-f6f2-495a-b683-0146db2d9c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
