<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>a07c2990-1480-4057-859f-71ce68c59b54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sectionContent-524']/div/slot/records-record-layout-row[6]/slot/records-record-layout-item/div/span/slot/lightning-input/lightning-datepicker/div/div/lightning-calendar/div/lightning-focus-trap/slot/table/tbody/tr/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > span.slds-day</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a8ae8057-c03b-40dd-abbd-e2b514e59625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-day</value>
      <webElementGuid>ea8919bb-1eab-42b6-8428-32b644bb7eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>21fb624d-f67b-48d8-9203-2c6d4bc9c11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec4ea0c3-f6ef-46af-b679-7a51648e03e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5aad658e-88c1-4534-8260-4951b1a46308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionContent-524&quot;)/div[@class=&quot;slds-form&quot;]/slot[1]/records-record-layout-row[@class=&quot;slds-form__row&quot;]/slot[@class=&quot;slds-grid slds-size_1-of-1&quot;]/records-record-layout-item[@class=&quot;slds-form__item slds-no-space&quot;]/div[@class=&quot;slds-grid slds-size_1-of-1 label-inline&quot;]/span[@class=&quot;test-id__field-value slds-size_1-of-1&quot;]/slot[1]/lightning-input[@class=&quot;slds-form-element slds-form-element_horizontal&quot;]/lightning-datepicker[1]/div[@class=&quot;slds-dropdown-trigger slds-dropdown-trigger_click slds-size_1-of-1 slds-is-open&quot;]/div[@class=&quot;slds-form-element__control slds-input-has-icon slds-input-has-icon_right&quot;]/lightning-calendar[1]/div[@class=&quot;slds-datepicker slds-dropdown slds-dropdown_left&quot;]/lightning-focus-trap[1]/slot[1]/table[@class=&quot;slds-datepicker__month&quot;]/tbody[1]/tr[1]/td[2]/span[@class=&quot;slds-day&quot;]</value>
      <webElementGuid>7f753e71-0b11-4059-b488-2fada9ac98cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-524']/div/slot/records-record-layout-row[6]/slot/records-record-layout-item/div/span/slot/lightning-input/lightning-datepicker/div/div/lightning-calendar/div/lightning-focus-trap/slot/table/tbody/tr/td[2]/span</value>
      <webElementGuid>d9f9a7b8-bb05-4a4f-a9e2-2e0c15840743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>ba44e4fc-a130-4b78-8efd-66cb9aec4d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>fc49c59d-05cf-4345-befa-5d2b76f94d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
