<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>e18d962b-c7cc-4b68-a2ce-a3a478a8f85a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;contact-header&quot;)/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-no-flex slds-grid slds-align-top&quot;]/div[@class=&quot;cProcessButton&quot;]/section[@class=&quot;slds-modal slds-fade-in-open&quot;]/div[@class=&quot;slds-modal__container&quot;]/div[@class=&quot;slds-modal__content slds-p-around_medium&quot;]/div[@class=&quot;slds-show cStartRecruitmentProcess&quot;]/div[@class=&quot;process-footer&quot;]/div[@class=&quot;button-bar&quot;]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8303b68c-8ba6-49c4-8f69-839898d660c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b213e8b9-e3a2-463d-a5d6-232b5856c79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>b937800b-bb12-45d2-ba37-7f19183c77f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1384:0</value>
      <webElementGuid>988cf881-7624-454b-8c1c-77fac42151b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>4451c300-cc33-4507-8aa4-3e9553c64f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-header&quot;)/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-col slds-no-flex slds-grid slds-align-top&quot;]/div[@class=&quot;cProcessButton&quot;]/section[@class=&quot;slds-modal slds-fade-in-open&quot;]/div[@class=&quot;slds-modal__container&quot;]/div[@class=&quot;slds-modal__content slds-p-around_medium&quot;]/div[@class=&quot;slds-show cStartRecruitmentProcess&quot;]/div[@class=&quot;process-footer&quot;]/div[@class=&quot;button-bar&quot;]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>7a57bb54-e390-46f0-a37e-fdf50cdf2cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>95834e7b-50d9-4446-b5a4-c20f4d17cefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div[2]/div/button</value>
      <webElementGuid>02865302-9298-4a84-a49f-f6f3a8bca164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::button[1]</value>
      <webElementGuid>5ddc8ade-1ddd-48a8-b012-306f527f0818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip'])[1]/following::button[1]</value>
      <webElementGuid>5e2e800d-e1bd-44b7-8351-3f5fb684f4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Authorization and Gender'])[1]/preceding::button[1]</value>
      <webElementGuid>0bebf587-a1d1-4dc3-8500-387af6004e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::button[1]</value>
      <webElementGuid>4755262d-4a5b-4c53-993d-4bce84a05e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>6ebb3950-e2f8-49ec-a5da-32cfeb7cd7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/button</value>
      <webElementGuid>969bf311-fe5d-4a5e-8944-043eda67b49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>263f584f-477f-4fba-9751-2156635b94b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
