<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test Standford US School Account</name>
   <tag></tag>
   <elementGuidId>cef44782-40ce-487f-a6e7-6505618f8876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contact-header&quot;]/div/div[2]/div[2]/section/div/div/div[2]/div/div[1]/div[2]/div/div/fieldset/div/div[1]/div[1]/div/div/div[4]/ul/li[1]/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[2]/div/div/fieldset/div/div/div/div/div/div[4]/ul/li/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slds-lookup__menu > ul.slds-lookup__list > li > span.slds-lookup__item-action.slds-media > div.slds-media__body > div.slds-lookup__result-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5afdd93-3803-462b-8f16-8e659d9091d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__result-text</value>
      <webElementGuid>8a0328d1-75b0-451d-8395-33d902de7c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>7:2472;a</value>
      <webElementGuid>e52c4d95-13f6-4118-91d7-daf8d73f7b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Standford US School Account</value>
      <webElementGuid>9f9ab70d-5b93-48a8-bc06-2a54720eea41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contact-header&quot;]/div/div[2]/div[2]/section/div/div/div[2]/div/div[1]/div[2]/div/div/fieldset/div/div[1]/div[1]/div/div/div[4]/ul/li[1]/span</value>
      <webElementGuid>04c53e0f-0a99-468a-a682-36df68a44fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[2]/div/div/fieldset/div/div/div/div/div/div[4]/ul/li/span/div/div</value>
      <webElementGuid>bc99fa71-ee02-4081-8bb0-60a4697e8052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('No results found for ', '&quot;', 'us school', '&quot;', '')])[1]/following::div[2]</value>
      <webElementGuid>627b2fda-f560-46ff-8797-274912e15a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Searching...'])[1]/following::div[6]</value>
      <webElementGuid>0fff6912-842a-4669-a992-ddcfa84dc14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US School'])[1]/preceding::div[1]</value>
      <webElementGuid>a94e001f-08e4-45bd-8112-64049cca1429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BA/BS Major'])[1]/preceding::div[3]</value>
      <webElementGuid>8f3744a9-6ad3-4058-9757-75f52498c587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Standford US School Account']/parent::*</value>
      <webElementGuid>112724ed-7715-4e76-bb76-4e777e6ef9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/span/div/div</value>
      <webElementGuid>11d50381-0f0a-400e-821f-1db6e8c93ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Test Standford US School Account' or . = 'Test Standford US School Account')]</value>
      <webElementGuid>ca3223c0-1a51-4b44-b1e4-bcfc6493cac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
