<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BABS School_input-5893</name>
   <tag></tag>
   <elementGuidId>0c1ec41a-5937-4a51-a4f5-5baa0ba5bd20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@type = 'text' and @placeholder = 'Select an option'])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='strike-lookup-5893']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#strike-lookup-5893</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f90e0c7-54f2-48a8-a325-6051cd77e9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>d14031d2-6ea5-4f87-a42b-5a11d944a79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>8a0d75c3-6252-4f19-8399-070c6edcfa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3df453b-d0fb-4972-9576-ca1273ca7a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebb1dfa6-6c3c-40b9-914a-98a2c3a8fb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-5893</value>
      <webElementGuid>5061ebdb-ab01-434c-8b63-5a739a8de8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strike-lookup-5893</value>
      <webElementGuid>5ac7b0b5-274d-4fdb-b8d4-f8b20c988a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select an option</value>
      <webElementGuid>3f179deb-9b1c-4b44-b4fd-a60acb10576d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__search-input slds-input js-template-lookup</value>
      <webElementGuid>f949f603-daf1-48b9-8fb7-2381d1826f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1621:0</value>
      <webElementGuid>2b7b1ff7-529a-4602-9f5e-d079f48826a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@type = 'text' and @placeholder = 'Select an option'])[1]</value>
      <webElementGuid>70ac7f8b-b50f-489a-b755-a4a845a05bdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='strike-lookup-5893']</value>
      <webElementGuid>2a5cefc4-487d-4f23-8978-dff360652422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/div[2]/div/div/fieldset/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>6105a608-465d-4b5b-8552-bfda12ed502e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d1ef9461-660c-405d-a5fd-b0d366d229a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input-5893' and @id = 'strike-lookup-5893' and @placeholder = 'Select an option']</value>
      <webElementGuid>1d1cc6e8-922d-4f93-8421-93e54dbca77e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
