<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip_Zip</name>
   <tag></tag>
   <elementGuidId>1d28a1d4-6ac8-46ce-9f99-a19644e37359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'Zip' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-525']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-525</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b2573d5-5f29-4379-b47e-a305f5404a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>78b97145-5419-4c71-a04a-8a20d10613fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-525</value>
      <webElementGuid>adae4731-8dbb-4136-b24e-405c591ed44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-525</value>
      <webElementGuid>45e8efc6-5a0d-48ae-8dee-d00c0f9a286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>fb5d995a-ea80-4cae-973d-638933c22299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>336f1c01-4179-484e-80d4-789b0741cc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ad74b9a-1f3c-49ed-8d31-6c9ca1cf9b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name = 'Zip' and @type = 'text']</value>
      <webElementGuid>fd09fc55-4913-4c9b-b97f-154afc0b189c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-525']</value>
      <webElementGuid>193b77a1-58d9-43e1-9295-4cbf6fb2052a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div/div[2]/div/div/fieldset/div/div[3]/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>bcc03202-432c-4321-9539-32f45fd46981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/fieldset/div/div[3]/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>dd9d24ff-bb36-491a-b177-26784c4b498c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-525' and @name = 'Zip' and @type = 'text']</value>
      <webElementGuid>186f06bd-509a-410b-bb45-8270cbb38a1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
