<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street_Street</name>
   <tag></tag>
   <elementGuidId>7a30bf2b-5e4d-4f7c-b921-2cd3f9047911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'Street' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-542']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-542</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c56f7c23-a450-4810-8881-09895350d370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>48793b37-f445-4758-bfea-d7fd810ece7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-542</value>
      <webElementGuid>44ef3204-fb9e-4dae-af48-618b82b683c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-542</value>
      <webElementGuid>03315e3d-9bd8-4a87-813a-5917d013f8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street</value>
      <webElementGuid>aa3ea68a-5ecf-4d4e-824b-ea4a27c60101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d97836de-012a-4ef8-84d8-2e0d4ef6f34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6a1b247-371c-445e-beb2-0fd0d91e193e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name = 'Street' and @type = 'text']</value>
      <webElementGuid>ab75ddb5-ee05-42f9-8bd8-1798e2c52aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-542']</value>
      <webElementGuid>997a0666-1569-4e4d-bd6e-e591cca23af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div/div[2]/div/div/fieldset/div/div/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>79bbb688-391d-4579-aee4-d6f9b781edfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/fieldset/div/div/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>de491d6e-29b9-45c5-853d-9bd978c9cf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-542' and @name = 'Street' and @type = 'text']</value>
      <webElementGuid>5ef1974c-752e-4dd0-8ff9-188a1ccc7b4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
