<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>State</name>
   <tag></tag>
   <elementGuidId>c2f6aa46-f658-460f-97b6-71df81d127c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'State']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1504:0']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af66e8ce-eab3-41e2-9ed6-3a47fe8b8514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9fd10d68-8d59-4f19-bb0a-61f0321c7b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1504:0</value>
      <webElementGuid>5a8ccfc7-c4a7-4843-8b7b-cfef4b953fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>1ff3e7a1-936f-449b-bb87-29add5dcd837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1515:0</value>
      <webElementGuid>52f67236-7559-4f1d-9f1d-9740f3ea91d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>fc80fb1a-4750-4386-b2d7-8d78811efd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AlabamaAlaskaAlbertaAndaman and Nicobar IslandsAndhra PradeshArizonaArkansasArunachal PradeshAssamBiharBritish ColumbiaCaliforniaChandigarhChhattisgarhColoradoConnecticutDadra and Nagar HaveliDaman and DiuDelawareDelhiDistrict of ColumbiaFloridaGeorgiaGoaGujaratHaryanaHawaiiHimachal PradeshIdahoIllinoisIndianaIowaJammu and KashmirJharkhandKansasKarnatakaKentuckyKeralaLakshadweepLouisianaMadhya PradeshMaharashtraMaineManipurManitobaMarylandMassachusettsMeghalayaMichiganMinnesotaMississippiMissouriMizoramMontanaNagalandNebraskaNevadaNew BrunswickNewfoundland and LabradorNew HampshireNew JerseyNew MexicoNew YorkNorth CarolinaNorth DakotaNorthwest TerritoriesNova ScotiaNunavutOdishaOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuducherryPuerto RicoPunjabQuebecRajasthanRhode IslandSaskatchewanSikkimSouth CarolinaSouth DakotaTamil NaduTelanganaTennesseeTexasTripuraUtahUttarakhandUttar PradeshVermontVirginiaWashingtonWest BengalWest VirginiaWisconsinWyomingYukon Territories</value>
      <webElementGuid>37b27d13-b0ec-44d9-8a61-c8072ff0a086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name = 'State']</value>
      <webElementGuid>7c7be626-270f-433a-aaf8-32436eb1faf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1504:0']</value>
      <webElementGuid>16d1f1d3-40a7-4e6b-8a46-f280c7d2bdbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div/div/div[2]/div/div/fieldset/div/div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>4d6ed02c-c603-4d33-bbdc-93c8fc40ee7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fef82ca8-3122-4f45-8070-0c6614ebfb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '1504:0' and @name = 'State' and (text() = 'AlabamaAlaskaAlbertaAndaman and Nicobar IslandsAndhra PradeshArizonaArkansasArunachal PradeshAssamBiharBritish ColumbiaCaliforniaChandigarhChhattisgarhColoradoConnecticutDadra and Nagar HaveliDaman and DiuDelawareDelhiDistrict of ColumbiaFloridaGeorgiaGoaGujaratHaryanaHawaiiHimachal PradeshIdahoIllinoisIndianaIowaJammu and KashmirJharkhandKansasKarnatakaKentuckyKeralaLakshadweepLouisianaMadhya PradeshMaharashtraMaineManipurManitobaMarylandMassachusettsMeghalayaMichiganMinnesotaMississippiMissouriMizoramMontanaNagalandNebraskaNevadaNew BrunswickNewfoundland and LabradorNew HampshireNew JerseyNew MexicoNew YorkNorth CarolinaNorth DakotaNorthwest TerritoriesNova ScotiaNunavutOdishaOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuducherryPuerto RicoPunjabQuebecRajasthanRhode IslandSaskatchewanSikkimSouth CarolinaSouth DakotaTamil NaduTelanganaTennesseeTexasTripuraUtahUttarakhandUttar PradeshVermontVirginiaWashingtonWest BengalWest VirginiaWisconsinWyomingYukon Territories' or . = 'AlabamaAlaskaAlbertaAndaman and Nicobar IslandsAndhra PradeshArizonaArkansasArunachal PradeshAssamBiharBritish ColumbiaCaliforniaChandigarhChhattisgarhColoradoConnecticutDadra and Nagar HaveliDaman and DiuDelawareDelhiDistrict of ColumbiaFloridaGeorgiaGoaGujaratHaryanaHawaiiHimachal PradeshIdahoIllinoisIndianaIowaJammu and KashmirJharkhandKansasKarnatakaKentuckyKeralaLakshadweepLouisianaMadhya PradeshMaharashtraMaineManipurManitobaMarylandMassachusettsMeghalayaMichiganMinnesotaMississippiMissouriMizoramMontanaNagalandNebraskaNevadaNew BrunswickNewfoundland and LabradorNew HampshireNew JerseyNew MexicoNew YorkNorth CarolinaNorth DakotaNorthwest TerritoriesNova ScotiaNunavutOdishaOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuducherryPuerto RicoPunjabQuebecRajasthanRhode IslandSaskatchewanSikkimSouth CarolinaSouth DakotaTamil NaduTelanganaTennesseeTexasTripuraUtahUttarakhandUttar PradeshVermontVirginiaWashingtonWest BengalWest VirginiaWisconsinWyomingYukon Territories')]</value>
      <webElementGuid>d06226b2-7058-453f-830e-1b231f83e575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
