<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Trainings</name>
   <tag></tag>
   <elementGuidId>37827063-c283-4965-a71a-6a34ed3d895a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Trainings' or . = 'Trainings')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Training__c']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slds-size_small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0eb372e-0593-4bbc-87ec-4bc6aedbb754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-size_small</value>
      <webElementGuid>6ba8c322-2df9-4c99-9864-932a4e2668c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trainings</value>
      <webElementGuid>9619b525-48f1-4ee0-b861-0b8bc52d55e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Training__c&quot;)/div[@class=&quot;slds-size_small&quot;]</value>
      <webElementGuid>cd4e1f86-bb83-4b09-a949-7fa02bb95538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Training__c']/div</value>
      <webElementGuid>235375f4-3112-48ba-9f37-e15ba7f4a209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[1]/following::div[2]</value>
      <webElementGuid>0c0822a7-a372-49f9-90d0-f9b4d6b1962d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/following::div[3]</value>
      <webElementGuid>19e81ed7-b820-4f63-aabe-0d528f1bc82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[3]/preceding::div[1]</value>
      <webElementGuid>8bce022e-f7c5-45e9-b57f-ccbb2727bce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-menu-item/a/div</value>
      <webElementGuid>5b33a340-c864-46f6-9141-9196b4e02181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Trainings' or . = 'Trainings')]</value>
      <webElementGuid>a9091559-29ef-4d9e-9696-9940fc7da0ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
