<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__trainingTarget</name>
   <tag></tag>
   <elementGuidId>078ca4d8-deff-4d4f-94a5-9fd3f31fea0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-206</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='TrainingTarget__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[2]/div/div[2]/lightning-input/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3053747-eb2c-4bcd-b62d-03c62aaaaae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>f9f19a05-6918-4bdf-8799-5839ab23e753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76f8cc75-24b1-49cb-b16b-601c9978492f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-206</value>
      <webElementGuid>e4696c2b-095b-4bc5-9608-3c8e1cc1ffcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7e8fe7c2-b52d-46ca-b314-56f6c73d07a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>0*[1-9][0-9]*</value>
      <webElementGuid>ff35d338-9498-479b-a584-266b58e9d45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trainingTarget</value>
      <webElementGuid>9caa35dc-b771-4ba5-bd73-bd96cd4ee2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='TrainingTarget__c']</value>
      <webElementGuid>ccdb2c28-bd75-452d-bd86-5f39bd699995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-206']</value>
      <webElementGuid>ef70ed89-253d-4f1e-83ed-514e795c576f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[2]/div/div[2]/lightning-input/div/input</value>
      <webElementGuid>e3b748b6-6dad-429a-ad68-a648b22e44ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/div/input</value>
      <webElementGuid>619952ee-13f0-4fe0-a268-b72ae69d871e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-206' and @name = 'trainingTarget']</value>
      <webElementGuid>65963f65-f3ae-4dfa-9459-275278b4bd5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
