<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trainer_input-4364</name>
   <tag></tag>
   <elementGuidId>b29327b8-26c5-4fa7-ae0b-db589d457e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#strike-lookup-4364</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//input[contains(@placeholder,'Search People')])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[3]/div[2]/div[3]/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c698c40-b84f-4ccb-9c88-b18d58fcb438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>89bc1a5b-7218-4cc1-9789-323d9405ca94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7077d53e-d78c-4cbc-9f14-e66b531d6264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>73a82d4c-5d8a-4947-aac6-35c18a2ac244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9db231fc-0b23-49a6-9648-362a6f719fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-4364</value>
      <webElementGuid>755a5c48-f1f1-4f0f-97be-ab9830f964b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strike-lookup-4364</value>
      <webElementGuid>73a5793a-b410-4e77-bcde-8d42d86a389c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Users...</value>
      <webElementGuid>5e4ea30d-6fe5-4b54-94f9-0b60afd0471b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__search-input slds-input js-template-lookup</value>
      <webElementGuid>45e2d22e-fa36-445b-9457-7465b60296fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2306:0</value>
      <webElementGuid>45f4583c-9b8f-443a-8dce-3f0035b9140f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[contains(@placeholder,'Search People')])[1]</value>
      <webElementGuid>26d43319-82a3-4359-9308-6d95a30bd23f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='strike-lookup-4364']</value>
      <webElementGuid>3d6e869e-1c5b-401a-9b1b-b4bdbf1b2170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[3]/div[2]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>58505610-7cb1-419f-bbd9-50df44e00f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>7c1aaa8e-390e-45af-a72a-a272b223163d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input-4364' and @id = 'strike-lookup-4364' and @placeholder = 'Search Users...']</value>
      <webElementGuid>ea93fc9d-f7fe-4083-b4b6-410ca536dca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
