<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-1581</name>
   <tag></tag>
   <elementGuidId>a4333d16-0292-44d7-8c0d-d1f7ec2695db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#strike-lookup-1581</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@placeholder,'Search Training Tracks')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>256bd9e5-147c-405c-8fc6-28a4c6af59e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>efbbabc8-c1fd-4ced-ab7a-4549a7865198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>21fbc616-f044-4b0c-805b-8bd50df4882b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2792c13-6d01-4775-b4af-34a2fff99333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e77c528a-70cd-45ef-a3c8-0f9b0c852142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input-1581</value>
      <webElementGuid>3b908b27-94ab-430f-b058-e06388e5d245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>strike-lookup-1581</value>
      <webElementGuid>7c62e2a2-37d0-4c91-9598-306bd06bbf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Training Tracks...</value>
      <webElementGuid>cb7808d1-a2cc-4627-b00c-1f82a213d800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-lookup__search-input slds-input js-template-lookup</value>
      <webElementGuid>5cf36745-9b1b-47a8-9dd7-a12153035766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2147:0</value>
      <webElementGuid>756a6191-1b61-4a64-97d7-5cc90ecf18fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@placeholder,'Search Training Tracks')]</value>
      <webElementGuid>ec8967fd-7e0f-48e1-a257-0691eb11829e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='strike-lookup-1581']</value>
      <webElementGuid>5eefa21d-69aa-487d-a08e-1caffbd6e82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[2]/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>22cdd907-0ef8-4ff8-b976-0d101b7df4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3955c46d-dd54-412b-9bea-77fcc4faa462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input-1581' and @id = 'strike-lookup-1581' and @placeholder = 'Search Training Tracks...']</value>
      <webElementGuid>dc744ff8-cf41-4f95-a6bf-bfc7315e8542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
