<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__startDate</name>
   <tag></tag>
   <elementGuidId>b3410e48-c0ea-4c1d-ac81-37e2462a15be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-246</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='StartDate__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[2]/div[2]/lightning-input/lightning-datepicker/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ddb20cd-4290-46fb-9553-db9487d4bbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>779c0ed4-f23c-4a05-9a87-ba62b1c54f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9c82f26-fcce-4292-9dcf-2e95752228aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-246</value>
      <webElementGuid>66d6726c-e727-422a-add7-f8a8893490d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>8b62d99c-b582-44fa-a3e4-327f46e409c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ec545000-6355-42f5-b582-279a14973e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='StartDate__c']</value>
      <webElementGuid>16339fb2-204e-47d7-adf8-55d6efe75b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-246']</value>
      <webElementGuid>d8010d8d-5b60-46b7-b87b-820ee6482cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/div/div/div[2]/div[2]/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>1bd72668-f3e1-4fbc-a593-d2e51b5a1dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>197f16f2-b673-4043-b506-0a8b9f8793ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-246' and @name = 'startDate']</value>
      <webElementGuid>41911dd1-e909-45e4-9817-fb9ff91071b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
