<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Reston- testing6Test Location_1</name>
   <tag></tag>
   <elementGuidId>ed8c3d47-27f0-4f24-9139-a0a20f6a26c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'trainingLocation']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='611:0']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d1dbde6d-3e17-4255-a17c-287346a519dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5529ecc-71fe-4aa1-aec4-9dfa52fd682e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>611:0</value>
      <webElementGuid>96e830cf-86e2-4340-9f1c-c3856f8fe2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>98d37aa5-c478-4a0a-aa32-19beda071cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>622:0</value>
      <webElementGuid>41b05753-e58c-4b09-b4f2-0a068d5e1e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trainingLocation</value>
      <webElementGuid>e85dc771-511e-4b8a-8cfe-f927b72a7382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reston- testing6Test Location</value>
      <webElementGuid>4ce6aee2-ef1a-4e31-95c9-572b0fd65a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;611:0&quot;)</value>
      <webElementGuid>04a656eb-2a4d-40d4-905f-728700b09874</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='611:0']</value>
      <webElementGuid>aaa127bf-41b8-4519-a254-10a52b51ca2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/div/div/div/div/div[3]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>404dcec6-885e-4eaa-ae17-d50fe77efa4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div/select</value>
      <webElementGuid>d70d99f4-5612-4d3c-ad99-d0faac5dab7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '611:0' and @name = 'trainingLocation' and (text() = 'Reston- testing6Test Location' or . = 'Reston- testing6Test Location')]</value>
      <webElementGuid>59b67119-2c86-4e6b-af30-19225b18a305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
