<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Report17</name>
   <tag></tag>
   <elementGuidId>49659bbd-ad32-4790-8e37-45e91d8f3c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[contains(@class,'instant-result-item__content')])[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::mark[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mark.data-match</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>f4566ced-030c-4a5e-95ac-c3781cf50f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data-match</value>
      <webElementGuid>95dc7e4e-13a8-46c0-b197-7a62b935c079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report17</value>
      <webElementGuid>fca3f87b-edd4-49fe-bdb5-1f593d209303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[contains(@class,'instant-result-item__content')])[2]</value>
      <webElementGuid>9c5edded-7ef1-42b4-8632-d34f6cbfb6ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suggestionsList-91']/search_dialog-instant-result-item/div/div[2]/span/lightning-formatted-rich-text/span/mark</value>
      <webElementGuid>ce01710f-a791-4924-86fe-bc4723bb4ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::mark[1]</value>
      <webElementGuid>c350817e-caec-4b70-bfe9-a0568e381c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search...'])[3]/following::mark[1]</value>
      <webElementGuid>aed96722-395b-4eb7-9a6e-229e6d7e9652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testContact17'])[1]/preceding::mark[1]</value>
      <webElementGuid>31a07485-3d85-4ebc-9431-ccbcd06517c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact • TestingXperts'])[1]/preceding::mark[2]</value>
      <webElementGuid>7354d31c-6d17-47ad-9514-c6974c60a5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Report17']/parent::*</value>
      <webElementGuid>cd84bbab-63a2-4797-b2cd-209f815a5ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mark</value>
      <webElementGuid>df482556-d87f-4d8c-83c3-da930e42f675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'Report17' or . = 'Report17')]</value>
      <webElementGuid>a051d69e-103f-4c45-aec6-2638c630a0d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
