<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TA-00055051</name>
   <tag></tag>
   <elementGuidId>ef9a9e02-8bdb-4f10-89e2-bd408bef17ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Training Class'])[1]/following::span[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Training Class'])[1]/following::span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#window</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7f1a0654-fea1-4d67-9d99-e87566313825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-proxy-id</name>
      <type>Main</type>
      <value>aura-pos-lib-1</value>
      <webElementGuid>101463c2-459a-4602-bf66-e85ddd0391a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>window</value>
      <webElementGuid>ae8c73df-cfcd-4508-988b-d617a7bdfb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TA-00055051</value>
      <webElementGuid>d2659593-27cd-49b2-a6ef-c37d6017f5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Training Class'])[1]/following::span[2]</value>
      <webElementGuid>4d97651c-c37d-4351-bb97-2bb120d5457e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='window']</value>
      <webElementGuid>e2c1fc4b-dd17-47eb-ae76-bab2a2d49434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-449']/div/slot/records-record-layout-row[7]/slot/records-record-layout-item/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a/slot/slot/span</value>
      <webElementGuid>5a8c1803-4600-45ff-ac79-4204e9512159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Training Class'])[1]/following::span[2]</value>
      <webElementGuid>2eb33c57-237f-4184-a055-15c589aeb94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Card ID'])[1]/following::span[4]</value>
      <webElementGuid>a7dafce0-4bd4-4ec3-9bdf-951833148cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open TA-00055051 Preview'])[1]/preceding::span[1]</value>
      <webElementGuid>aed36e81-6091-4628-a702-e78c7077a8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay Details'])[2]/preceding::span[3]</value>
      <webElementGuid>ed80f1fd-1944-450e-9423-8eff6a04f1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TA-00055051']/parent::*</value>
      <webElementGuid>41011d03-56bc-4d01-b950-f574e7df564e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[7]/slot/records-record-layout-item/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a/slot/slot/span</value>
      <webElementGuid>43e779d3-d233-4aa1-9f83-801d16d9bc82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'window' and (text() = 'TA-00055051' or . = 'TA-00055051')]</value>
      <webElementGuid>2d8f0249-a3c3-4d17-9da2-9d04497aec9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
