<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_7</name>
   <tag></tag>
   <elementGuidId>d5b33dfe-2224-4ca4-9b06-5d161f8de02e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span[text()='7'])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='SAT'])[1]/following::span[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f84790b5-3e38-4e87-89fa-5f4ee4b0fc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-day weekday DESKTOP uiDayInMonthCell--default</value>
      <webElementGuid>eb6b6fcf-8659-45c8-8be1-005d4ba3a94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>613:0</value>
      <webElementGuid>bb06d9fa-b768-435c-aee0-370eb22fb565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>uiDayInMonthCell--default</value>
      <webElementGuid>9f1b5014-d2ea-4a40-a7a7-e9b3f49e8ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>971d84a7-7baf-4ce7-bc86-65eeefb7d8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[text()='7'])[1]</value>
      <webElementGuid>5f6bc667-9f63-46d0-b7d3-dfe7e20d40a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='535:0']/div/div[2]/table/tbody/tr[2]/td[2]/span</value>
      <webElementGuid>55800860-31d8-400f-960c-41ce7e368937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAT'])[1]/following::span[9]</value>
      <webElementGuid>af1de6ee-103c-45ac-a61f-ba351321bed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRI'])[1]/following::span[9]</value>
      <webElementGuid>ade32ada-b127-46c6-bf62-8649a6263aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::span[34]</value>
      <webElementGuid>2d5ba061-b37c-4be2-9b0b-4197ce65ca42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7']/parent::*</value>
      <webElementGuid>ebec8e33-f31f-4965-96a4-8f41b8fd66e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span</value>
      <webElementGuid>074c7704-7080-4c31-85ef-00158f55ec5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '7' or . = '7')]</value>
      <webElementGuid>a31123a9-1ae1-4690-a75b-29a0f4bbbabc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
