<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email-task</name>
   <tag></tag>
   <elementGuidId>a61a865e-33c3-44a4-b2c4-057c509e06d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(text(),'Scored')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(text(),'Scored')]</value>
      <webElementGuid>60da8680-bb34-4a92-a541-ace2e8015807</webElementGuid>
   </webElementProperties>
</WebElementEntity>
