<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__TentativePOEndDate__c</name>
   <tag></tag>
   <elementGuidId>91256772-bac3-4bdd-b310-4057c39225cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1276</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'TentativePOEndDate__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1276']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bce5b8ed-e63e-448b-9a96-6157da3c58f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>cec96267-7ab2-4ae0-add3-ae4228cbd46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08422f9e-07f0-43fa-a847-cd5f43275cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1276</value>
      <webElementGuid>49b629c8-8c7b-45f1-b4f7-85dfaaad0a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TentativePOEndDate__c</value>
      <webElementGuid>98559031-d5ad-471c-b5d4-5f3e4b35b3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d953d150-ec74-4400-8a9f-2f89c2b4bbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-message-1276</value>
      <webElementGuid>6cd0e1ab-57da-4ea7-a104-175f0427c91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1276&quot;)</value>
      <webElementGuid>2316401c-ae2a-4b74-8e31-f578f8cfb8fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1276']</value>
      <webElementGuid>18e190ab-5535-4a7a-b266-e2e388df8a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-818']/div/slot/records-record-layout-row[2]/slot/records-record-layout-item[2]/div/span/slot/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>421cf98b-be84-48ae-9770-9d4f724961f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>ba195e7f-2075-4a47-8495-a558a68eb735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-1276' and @name = 'TentativePOEndDate__c']</value>
      <webElementGuid>1db4b2bd-16c7-454b-8995-37e147869982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
