<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MobilePhone</name>
   <tag></tag>
   <elementGuidId>752ff109-f658-48a5-bf5b-bc607adb2db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'MobilePhone' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-448']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-448</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf73484e-0eac-4398-ad26-3180c775b8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>d7313bfe-e32f-4f9e-a231-1856fc8de2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-448</value>
      <webElementGuid>01237755-da4b-4a7e-aeff-4372668f019e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-448</value>
      <webElementGuid>b05fa716-5105-411a-b9aa-e82a5f866154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>0ca13356-b4ec-4d03-bcbe-1115b823c5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MobilePhone</value>
      <webElementGuid>66aff238-a758-4a18-8e17-dd37c78915a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1ba06ad-0de2-4bba-80d9-589b70786c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b1bc8d8-2ef5-4de5-bcd8-b19d66ddbe67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-448&quot;)</value>
      <webElementGuid>50cc7821-0249-4a13-ab2a-cf64d633ec32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-448']</value>
      <webElementGuid>f4d95949-1a80-4e53-a8b4-373052e48ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-229']/slot/flexipage-column2/div/slot/flexipage-field[3]/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>c7b11ba5-c081-402f-9332-4b29b85a2747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-field[3]/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>62f6212d-19ea-40de-b94e-878ebf38a481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-448' and @name = 'MobilePhone' and @type = 'text']</value>
      <webElementGuid>663662e8-cbc6-4a77-b2fd-3dbb4b80d506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
