<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search apps and items_input-90</name>
   <tag></tag>
   <elementGuidId>a96a8aa0-3701-424c-bd22-595b89827fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@type='search'])[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//one-app-launcher-search-bar/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-90</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5905177b-4074-4624-8d58-e9a4d1fa6499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>a87f18e5-3b55-4558-ac6a-7972322affc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>5fd820ab-d19e-43ce-ad58-6d2a20717060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-90</value>
      <webElementGuid>19786186-4593-490a-8084-13a09210fb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search apps and items...</value>
      <webElementGuid>1eb12ca4-7535-4866-92e6-c9c5bffe45c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>90e0cc48-25c9-4ed6-b1f9-20a6e936d186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e5e2bbac-2248-41c7-a46f-7f869bf60166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>al-menu-dropdown-apps-id</value>
      <webElementGuid>17af6810-4cac-428d-802b-72fb819b1399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@type='search'])[3]</value>
      <webElementGuid>0030fdf7-442e-4087-a10e-64f5ace12db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-90']</value>
      <webElementGuid>19347960-a052-4728-a66b-6c3841bdc1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_783:0']/one-app-launcher-menu/div/one-app-launcher-search-bar/lightning-input/div/input</value>
      <webElementGuid>93873c7b-e4a4-4741-b8a4-2cc2c3bfadbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-search-bar/lightning-input/div/input</value>
      <webElementGuid>761e1d7c-4fad-455a-b7a2-3524542fd2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-90' and @placeholder = 'Search apps and items...']</value>
      <webElementGuid>2d614182-c5a2-452c-86b3-a0f0d310de33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
