<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Interview record id</name>
   <tag></tag>
   <elementGuidId>805c9b22-a508-4531-bd9d-a83124a19298</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0200</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(text(),'INT')])[3]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='0200']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ab6eaae1-8d6a-4f8e-9ca8-653f6944a918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hours</name>
      <type>Main</type>
      <value>02</value>
      <webElementGuid>c75e7dc6-86d9-4d99-b56a-069c2152bfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb841e6a-be21-4bdb-b103-528f2827ef94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>85686046-dc2f-426b-ac6c-480feaaaa663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minutes</name>
      <type>Main</type>
      <value>00</value>
      <webElementGuid>d9c2f8a7-d086-4cef-a350-96c31a78cb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0200</value>
      <webElementGuid>0561bd5d-973f-47cc-a3c1-f8c5251f09a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2:00 AM</value>
      <webElementGuid>8d36675d-27c2-43e5-ba11-8c3150b0de79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(text(),'INT')])[3]</value>
      <webElementGuid>afd90b4b-6aea-4b2c-bf83-4682fd7a8f3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='0200']</value>
      <webElementGuid>30c87436-ce80-4cee-a47d-1dca543937b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1424:0']/div/ul/li[5]</value>
      <webElementGuid>d06e909f-5ef7-41e3-8541-3ff9bf254e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '0200', '&quot;', ')')])[1]/following::li[5]</value>
      <webElementGuid>5b970a09-dfd0-475c-ae0b-9c7e21a966b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::li[5]</value>
      <webElementGuid>debf8b49-4f7e-46ee-a34c-65e1a4b4d4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2:00 AM']/parent::*</value>
      <webElementGuid>db5977ae-8660-4d3c-b983-5d75c6752a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/ul/li[5]</value>
      <webElementGuid>c7a430f3-f80c-41f2-9f20-9ddb6f0d395f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '0200' and (text() = '2:00 AM' or . = '2:00 AM')]</value>
      <webElementGuid>a567189a-b232-46e5-9711-e66699c3cacd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
