<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--None--Fluency of SpeechClarity of _ed6a14</name>
   <tag></tag>
   <elementGuidId>55986b17-1ec7-402c-9209-7167c7e4dcd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Soft Skills Feedback'])[1]/following::select[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-interview_-record_-page___-interview__c___-v-i-e-w/forcegenerated-flexipage_interview_record_page_interview__c__view_js/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[2]/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/div[2]/section/div/div/div/div/div/fieldset/div/div[4]/div[2]/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d4d354d9-23a4-45b4-bcb4-b4166f7a4c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab5f8e0e-055e-4f96-94ea-a7a798b65df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2787:0</value>
      <webElementGuid>ca566cb5-2e27-441c-9d71-4e5e54f4ce50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>76a1d4a1-a43c-4e02-b5eb-0c2348fa929e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2799:0</value>
      <webElementGuid>d3f8e94b-b6f5-492e-bc1e-675eb547e325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Soft Skills Feedback</value>
      <webElementGuid>6beadc19-5aa5-4b66-90d3-318a5f7e7701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--None--Fluency of SpeechClarity of ThoughtListeningConfidenceAttitudeOther</value>
      <webElementGuid>cea2d21f-273a-4b10-ba48-9c474408558a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soft Skills Feedback'])[1]/following::select[1]</value>
      <webElementGuid>eee7ba19-71f8-496b-8f0d-560b6d7aa77c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='2787:0']</value>
      <webElementGuid>4422516a-000d-48a0-8912-a8a2ea22bcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-interview_-record_-page___-interview__c___-v-i-e-w/forcegenerated-flexipage_interview_record_page_interview__c__view_js/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[2]/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/div[2]/section/div/div/div/div/div/fieldset/div/div[4]/div[2]/div/div/div/select</value>
      <webElementGuid>2d1eb09a-73cf-4d68-894d-c840cb19eb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soft Skills Feedback'])[2]/following::select[1]</value>
      <webElementGuid>b5bed764-83b5-4e03-ad8a-51d7adabf7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Feedback'])[1]/following::select[2]</value>
      <webElementGuid>90e8d031-39b8-4bd1-a1e0-85c1b9d32ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technical Feedback (Freeform)'])[2]/preceding::select[1]</value>
      <webElementGuid>aa29da72-edc9-49d7-a7a9-8c833c6ca16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soft Skills Feedback (Freeform)'])[2]/preceding::select[1]</value>
      <webElementGuid>9e85d829-723b-4430-bb67-3673c534f81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/select</value>
      <webElementGuid>92784dc8-d051-4832-9f1b-e3f53fccb70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '2787:0' and @name = 'Soft Skills Feedback' and (text() = '--None--Fluency of SpeechClarity of ThoughtListeningConfidenceAttitudeOther' or . = '--None--Fluency of SpeechClarity of ThoughtListeningConfidenceAttitudeOther')]</value>
      <webElementGuid>1cadcf76-1112-4bf9-8a23-4f5352cc1973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
