<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contact Record Type</name>
   <tag></tag>
   <elementGuidId>4ef6de23-27cc-451d-a22d-6ec017a46d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[(text() = 'Revature')])[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-section-content-192']/slot/flexipage-column2[2]/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/records-record-type/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.recordTypeName.slds-grow.slds-truncate > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9069a2cb-fa44-48d8-8339-6e1071b31a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Revature</value>
      <webElementGuid>ac8f74ab-c825-446d-b1e7-a1e2a0afa457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[(text() = 'Revature')])[4]</value>
      <webElementGuid>4df06e81-df52-4cbf-b67b-5196720d1b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-192']/slot/flexipage-column2[2]/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/records-record-type/div/div/span</value>
      <webElementGuid>4a8a7a19-6fd3-49fe-b4fa-a0a7a06eea0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-type/div/div/span</value>
      <webElementGuid>c4da8765-6d65-49a6-a76f-4124daf8586a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Revature' or . = 'Revature')]</value>
      <webElementGuid>90e2210e-e35e-482f-ae8d-ba17f393d538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
