<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Master stage as Qualifying</name>
   <tag></tag>
   <elementGuidId>5a760fba-a789-4e88-bb04-996e72d231dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Qualifying' or . = 'Qualifying')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-section-content-192']/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/lightning-formatted-text</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-section-content-192 > slot[name=&quot;columns&quot;] > flexipage-column2.column.flex-width > div.slds-col.slds-p-horizontal_small.slds-p-vertical_x-small > slot.column > flexipage-field > slot > record_flexipage-record-field.slds-grid.slds-col.slds-has-flexi-truncate > div.slds-grid.slds-size_1-of-1.label-stacked.undefined > div.slds-form-element.slds-hint-parent.test-id__output-root.slds-form-element_readonly.slds-form-element_stacked > div.slds-form-element__control > span.test-id__field-value.slds-form-element__static.slds-grow.word-break-ie11.is-read-only > slot[name=&quot;output&quot;] > lightning-formatted-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-formatted-text</value>
      <webElementGuid>33fcabcc-066e-4408-923f-73a71b008300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-output-element-id</name>
      <type>Main</type>
      <value>output-field</value>
      <webElementGuid>da22f86e-3b77-41c0-9640-58ea5c4479e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>slot</name>
      <type>Main</type>
      <value>output</value>
      <webElementGuid>7b35ae6d-2a0f-44fd-be25-e2e0b0797983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Screening</value>
      <webElementGuid>0aef6211-8a7c-409f-80cc-7015f2974812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[(text() = 'Qualifying' or . = 'Qualifying')]</value>
      <webElementGuid>c7731a1c-6a22-45c8-8c39-27ae4ccc35e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-192']/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/lightning-formatted-text</value>
      <webElementGuid>159a5aa4-ff27-4b8c-9901-096e7383a240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-component2[5]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/div/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/div[2]/span/slot/lightning-formatted-text</value>
      <webElementGuid>29b72bc4-5752-4181-a54f-ae7af051dcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-formatted-text[(text() = 'Screening' or . = 'Screening')]</value>
      <webElementGuid>0b8f40ea-845a-46b8-af8b-7b5c11241444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
