<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_Email</name>
   <tag></tag>
   <elementGuidId>a34eaade-4205-4056-b194-c189e5785190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'slds-input' and @name = 'Email']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//records-record-layout-row[6]/slot/records-record-layout-item/div/span/slot/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-201</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a31dd10b-b35d-4089-b00e-13efd9648329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>618dfd77-4dfc-4e36-a7ea-9aa58107a6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38f969be-0a96-46f2-9ad6-01e7f156b9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-201</value>
      <webElementGuid>a80fd662-c95f-4910-8873-ba2588ecb362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a682e7d1-f9df-4368-92cd-1e0cc77ffcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>88c2042e-3382-4e86-a7bf-39e6dfab3089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>dfde3c96-cb0c-48ac-ae4f-8f2461b104b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//records-record-layout-row[6]/slot/records-record-layout-item/div/span/slot/lightning-input/div/input)[1]</value>
      <webElementGuid>9e09a52d-805d-429d-897b-c6145a09c145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-201']</value>
      <webElementGuid>96c4d061-5995-4bc7-9f90-0142f6a51497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-154']/div/slot/records-record-layout-row[6]/slot/records-record-layout-item/div/span/slot/lightning-input/div/input</value>
      <webElementGuid>41c4313c-6bb2-4f66-9aa8-116ad0199e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-row[6]/slot/records-record-layout-item/div/span/slot/lightning-input/div/input</value>
      <webElementGuid>940e6ae9-e03a-4d89-9f99-7c583d05a2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-201' and @name = 'Email']</value>
      <webElementGuid>21b3f8a4-45f9-4ee0-ad14-633d98476595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
