<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile_MobilePhone</name>
   <tag></tag>
   <elementGuidId>2c6f025f-95ab-4b01-bf98-5ba44bcb422e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'slds-input' and @name = 'MobilePhone']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//slot/lightning-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-177</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcbcccde-4362-4c24-9600-e75ca75aa94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>d3a98c4b-601b-4160-ba20-778827bcbc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d4d4f9b-046c-4d98-939f-03aba673b649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-177</value>
      <webElementGuid>9cbea231-41ca-4199-b6b6-ee9ee3283212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9d8a4dec-9662-4c80-b4ae-253c82a70629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MobilePhone</value>
      <webElementGuid>24ed1ae3-28c5-4d23-ac73-46ba6f196d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//slot/lightning-input/div/input</value>
      <webElementGuid>5175ef26-31e8-43bb-922c-c8aea00add53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-177']</value>
      <webElementGuid>420407dd-2494-4867-9add-08238edbd052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-135']/div/slot/records-record-layout-row[5]/slot/records-record-layout-item/div/span/slot/lightning-input/div/input</value>
      <webElementGuid>5cb1524e-dbed-46f1-a02f-87fb224fcc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//slot/lightning-input/div/input</value>
      <webElementGuid>391e6574-dde7-46cb-9358-fcaf5b212cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-177' and @name = 'MobilePhone']</value>
      <webElementGuid>90a5f47f-6915-4363-b408-efa75830ed34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
