<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Qualifying</name>
   <tag></tag>
   <elementGuidId>90859716-29c6-444f-9210-ad71dd32d562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//lightning-base-combobox-item[2]/span[2]/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[3]/following::span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-173-1-173 > span.slds-media__body > span.slds-truncate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a56c52a-258d-452a-8cd6-11faf508fd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>2f9934e8-fd6f-4522-bde1-ead8da848d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qualifying</value>
      <webElementGuid>d4152400-cd18-45ef-97a2-9edd3ef33891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qualifying</value>
      <webElementGuid>c788bcfc-0cf5-4902-9a2b-d61353f28050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[2]/span[2]/span</value>
      <webElementGuid>af15b468-d9c4-4b68-a9e2-7b116931c882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-173-1-173']/span[2]/span</value>
      <webElementGuid>fe5209c1-345a-481a-93c8-34554a143150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[3]/following::span[3]</value>
      <webElementGuid>4ed95264-17da-4533-9564-407f1eab43eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[2]/following::span[6]</value>
      <webElementGuid>3df802db-8669-4d2b-ab1f-c30a25e1be24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career Coach'])[2]/preceding::span[2]</value>
      <webElementGuid>a508052c-cc96-4781-bc8b-f5a87dc366e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment'])[7]/preceding::span[5]</value>
      <webElementGuid>1e960b3b-4b43-4a2c-918a-c8711466d1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[2]/span[2]/span</value>
      <webElementGuid>55dc2be0-b05b-4428-bc5b-e6bd3323143c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Qualifying' and (text() = 'Qualifying' or . = 'Qualifying')]</value>
      <webElementGuid>baf46da4-01ca-4a57-8467-71ea6b621579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
