<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Initial Contact Task</name>
   <tag></tag>
   <elementGuidId>fdd6358b-ef54-4079-bdbe-755db45f131b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class='subjectLink slds-truncate']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section_2023-11']/ul/li/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/a/del</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>del</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>del</value>
      <webElementGuid>5306720b-dc8d-4a3a-8439-484551157413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>71:1547;a</value>
      <webElementGuid>8a4c92a3-afa3-4f1e-9b4f-2b0d39bfeaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Initial Contact: Demo21Automation21 TestContact21</value>
      <webElementGuid>fa2fac1e-5f1d-4565-a34d-eed2463eab26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class='subjectLink slds-truncate']</value>
      <webElementGuid>86907690-210a-4e93-8bbb-570e2740d4ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section_2023-11']/ul/li/div/div/div[2]/div[2]/div/div/div/div[2]/div/div/a/del</value>
      <webElementGuid>f1b28e1b-7ef4-4b22-8945-349d2ad580a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//del</value>
      <webElementGuid>e7f1cc4c-22d3-47fd-8293-0d6d54753c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//del[(text() = 'Initial Contact: Demo21Automation21 TestContact21' or . = 'Initial Contact: Demo21Automation21 TestContact21')]</value>
      <webElementGuid>3d12a997-30c0-4c6f-a1e5-df2856b047ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
