<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date is On or After_startDateCutoff</name>
   <tag></tag>
   <elementGuidId>c7b4168c-52eb-49d3-8117-5fccbf9a91b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/lightning-input/lightning-datepicker/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1026']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-1026</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14bc77cb-8f01-4662-96ac-2963d298259d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>3f2426fa-63b5-4144-aa36-dd8f9fd9284d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c6e8021-d861-47e1-bee1-31a4f22cc228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1026</value>
      <webElementGuid>7f603e21-45bf-47b2-b584-d6d81a338216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startDateCutoff</value>
      <webElementGuid>f9233340-5cf0-4489-9e03-cc232bc5999e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>90e4eb25-b54a-4d6d-9b94-ffa057bddd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>33b8f06a-60f1-4520-a57f-f809744178b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1026']</value>
      <webElementGuid>94db41d6-0051-4b09-9d7c-a335bdbb6f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-header']/div/div[2]/div[2]/section/div/div/div[2]/div/div/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>529df2d8-7795-4f22-80ca-140f9aa84a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>43cf4ac7-b29a-4bb1-8a6d-1d7c6430e7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-1026' and @name = 'startDateCutoff']</value>
      <webElementGuid>2ae47555-2caf-4031-bef3-0bac570870cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
