<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last training class</name>
   <tag></tag>
   <elementGuidId>d8a43099-b8c6-45b7-91be-0bfd59249d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(text(),'TA')])[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='field-section-content-188']/slot/flexipage-column2/div/slot/flexipage-field[6]/slot/record_flexipage-record-field/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-section-content-188 > slot[name=&quot;columns&quot;] > flexipage-column2.column.flex-width > div.slds-col.slds-p-horizontal_small.slds-p-vertical_x-small > slot.column > flexipage-field:nth-of-type(6) > slot > record_flexipage-record-field.slds-grid.slds-col.slds-has-flexi-truncate > div.slds-grid.slds-size_1-of-1.label-inline > div.slds-form-element.slds-hint-parent.test-id__output-root.slds-form-element_readonly.slds-form-element_horizontal > div.slds-form-element__control > span.test-id__field-value.slds-form-element__static.slds-grow.word-break-ie11.is-read-only > slot[name=&quot;output&quot;] > force-lookup > div.slds-grid > records-hoverable-link.slds-grow.flex-wrap-ie11 > div.slds-grid > a.flex-wrap-ie11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30020a8a-1228-4eee-85e7-638ac5c8203f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-wrap-ie11</value>
      <webElementGuid>ea8f6cbf-3c87-4063-85bf-fb383678e886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/r/TrainingAssignment__c/a12Su0000000MF3IAM/view</value>
      <webElementGuid>8f2395b5-5e2c-451f-b359-61325f14b9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1717218d-eb85-4ec8-8a17-7cf59eeaad75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TA-00062529</value>
      <webElementGuid>3514eb0b-d939-442a-a6ae-0d953bbb22d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(text(),'TA')])[1]</value>
      <webElementGuid>ca618c80-8348-4161-a773-5596c028eb8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-188']/slot/flexipage-column2/div/slot/flexipage-field[6]/slot/record_flexipage-record-field/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a</value>
      <webElementGuid>91a870e1-1fff-4342-a1fb-a86959f7f517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/TrainingAssignment__c/a12Su0000000MF3IAM/view')]</value>
      <webElementGuid>f382bd9c-0e06-4585-b054-c67eaf26fafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-component2[10]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/div/slot/flexipage-column2/div/slot/flexipage-field[6]/slot/record_flexipage-record-field/div/div/div[2]/span/slot/force-lookup/div/records-hoverable-link/div/a</value>
      <webElementGuid>12a7ef44-1b60-4b0f-ad63-4ff47f3f956c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lightning/r/TrainingAssignment__c/a12Su0000000MF3IAM/view' and (text() = 'TA-00062529' or . = 'TA-00062529')]</value>
      <webElementGuid>fcb92a71-bc7e-4434-955b-c3cb6422caae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
