<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Training</name>
   <tag></tag>
   <elementGuidId>768c9102-9972-4a76-97d1-8f659a04b435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr/th/lightning-input/lightning-primitive-input-radio/div/span/label/span[@class='slds-radio_faux']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr/th/lightning-input/lightning-primitive-input-radio/div/span/label/span[@class='slds-radio_faux']</value>
      <webElementGuid>e8e6d0f6-399e-48f0-93da-acc58623200b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
