<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Opportunities</name>
   <tag></tag>
   <elementGuidId>75dfb223-4ae0-4a80-9e58-e19e9072608c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Opportunity']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Opportunity&quot;)/div[@class=&quot;slds-size_small&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Opportunity > div.slds-size_small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9437cce0-ba1a-468c-a3be-fa089a1e9280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-size_small</value>
      <webElementGuid>d89fde53-2235-4117-b777-490d369d4e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Opportunities</value>
      <webElementGuid>b6d729e7-4dc8-4de8-a025-7804536cebdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Opportunity&quot;)/div[@class=&quot;slds-size_small&quot;]</value>
      <webElementGuid>d544c5a2-cb44-4f2f-aa14-95e088678251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Opportunity']/div</value>
      <webElementGuid>097cd71b-bd6e-4b7b-b389-f773b7140fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opportunities'])[1]/following::div[1]</value>
      <webElementGuid>19818d54-dff6-4e5e-a181-7a53299fb426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items'])[1]/following::div[3]</value>
      <webElementGuid>a314ab34-2cf7-464c-88d4-ff3770527647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[3]/preceding::div[1]</value>
      <webElementGuid>bb4edb26-14b5-49b2-b94b-5570ca333dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//one-app-launcher-menu-item[2]/a/div</value>
      <webElementGuid>62c121f5-b575-4e6b-bd2e-09f4cb890cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Opportunities' or . = 'Opportunities')]</value>
      <webElementGuid>30981afd-02b6-4c4b-9564-cc1b667a87d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
