<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Name</name>
   <tag></tag>
   <elementGuidId>0cc72b46-afa0-4288-948a-90630cfc075d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-212</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'Name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//records-record-layout-base-input/lightning-input/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b145a4a4-fac4-4585-a812-87930311d780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>969aa3bd-dff4-4e80-8cb1-138004f25cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a42d1b07-76f1-4cf3-b298-26f0bcc90947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-212</value>
      <webElementGuid>ede9f9b1-c3d1-4584-a281-7aaf1023f7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>08596735-4a23-4b9e-917b-9b4ecc9ba71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>4ecaa422-9c67-4d8e-a9e1-c798040d181e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name = 'Name']</value>
      <webElementGuid>a6438395-3864-41d6-a12d-221e9ae88cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-212']</value>
      <webElementGuid>3a6605ab-b633-47f8-921a-d17c1ae1b181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-200']/div/slot/records-record-layout-row[2]/slot/records-record-layout-item/div/span/slot/records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>78ba72de-a255-4354-a43c-93ffbb8d7fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//records-record-layout-base-input/lightning-input/div/input</value>
      <webElementGuid>8774df9c-7f06-4530-83e6-12b7633aabda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-212' and @name = 'Name']</value>
      <webElementGuid>6c92ad24-520d-46e0-bbed-22238f29a77a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
