<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OriginalQuantity__c</name>
   <tag></tag>
   <elementGuidId>50b858a0-851d-4b22-bb2b-c86f1d60afc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-367</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'OriginalQuantity__c' and @type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-367']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be1ca4bb-1ac9-46da-af91-a4f1e7238e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>ca1b1a92-d2b5-47db-a5a1-ddacd60edd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-367</value>
      <webElementGuid>c719bc38-1c93-4d4f-a9b9-cd3cc788278f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-367</value>
      <webElementGuid>89fd7d8a-0b29-4ecb-bd66-4014572ca23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>08e9f3c2-2754-4c9c-8a3b-909c2a42cf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OriginalQuantity__c</value>
      <webElementGuid>5dd99021-ff6b-42cd-b98a-be636572d99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87577763-ff3e-48ac-8a34-ffedfed360cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>4c38c06b-95e1-4507-9579-02a5bd52a4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19adb4ef-81f1-4939-a25a-ef16d5732ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-367&quot;)</value>
      <webElementGuid>b1713790-9060-4087-bdb8-9e91aa9ff1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-367']</value>
      <webElementGuid>5dbf4f9c-f5e1-4172-bfb2-73de4aff58cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-155']/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>3f2030f0-000f-4845-98c3-a3e49db93e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-field[2]/slot/record_flexipage-record-field/div/div/slot/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>2d2d1d6e-0b27-479c-b924-67f0027574a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-367' and @name = 'OriginalQuantity__c' and @type = 'text']</value>
      <webElementGuid>c7a6d77a-0c09-49ff-888e-5eebed6ce853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
