<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_Amount</name>
   <tag></tag>
   <elementGuidId>3ca0c397-34b9-43be-8bde-afaef3c54fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-282</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'Amount']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-282']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9628a209-0424-4d27-8832-00ea69e66db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>abf8a872-5fe6-4500-b87c-cbc4df711fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5472a7af-981a-4699-a66e-b3bd915345d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-282</value>
      <webElementGuid>7533bc6a-0caa-4011-a29f-9cd55bbc7bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>1aac7030-9543-438c-bdc5-8e8e51703135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>68f2265b-0377-471a-b287-468ce303f93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>f104f11d-8fc5-4cca-a518-2b219495bf02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-282&quot;)</value>
      <webElementGuid>1566e6db-85b7-40b9-bbe5-992756a43330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-282']</value>
      <webElementGuid>848c24af-49fb-410e-b71c-ac1a603a27d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-276']/div/slot/records-record-layout-row/slot/records-record-layout-item[2]/div/span/slot/sfa-input-opportunity-amount/lightning-input/div/input</value>
      <webElementGuid>2fc37bcd-f7b0-4f9f-b946-3c4f17b5165a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sfa-input-opportunity-amount/lightning-input/div/input</value>
      <webElementGuid>a84fadcf-b9e7-4d86-b16e-0fdaea60d458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-282' and @name = 'Amount']</value>
      <webElementGuid>7caebaa8-a886-458e-9ca9-662b42b3888c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
