<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SOWSigned__c</name>
   <tag></tag>
   <elementGuidId>6dd4f90e-7db0-4b81-a1b6-f66c72ccf9ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-335</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'checkbox' and @name = 'SOWSigned__c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-335']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a61c9ebc-ce4e-4e5c-869e-52858f508e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>81cba658-fe21-491e-9434-81c1f6baec5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eac46e94-306f-44a7-b3a2-ea5f5940098b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-335</value>
      <webElementGuid>9bed4a5b-194b-4f3c-af17-5c99d99fa958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SOWSigned__c</value>
      <webElementGuid>80476a4f-6bce-4bb1-a4c5-ed792f6c5f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'SOWSigned__c']</value>
      <webElementGuid>411b5fab-fa1f-44da-9e6a-fe58359cd640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-335']</value>
      <webElementGuid>a3e720cc-dfff-401b-848b-ed4194ab7390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='field-section-content-114']/slot/flexipage-column2/div/slot/flexipage-field/slot/record_flexipage-record-field/div/div/slot/records-record-layout-checkbox/lightning-input/lightning-primitive-input-checkbox/div/span/input</value>
      <webElementGuid>b742b2b0-a449-494f-a826-131a247321c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>d916fe67-af5a-471b-82d1-7d00c090a351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox-335' and @name = 'SOWSigned__c']</value>
      <webElementGuid>81f6858f-4123-44b0-9128-f36a8c219241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
