<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CloseDate</name>
   <tag></tag>
   <elementGuidId>85a58bf7-1e27-450e-84cb-f08e4368bada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-206</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//lightning-datepicker/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-datepicker/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5fce110-4b28-413e-81af-871c67064120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>61bd513e-edcc-498c-b6e8-3a36fb272fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>906a98e6-1735-4e00-b69c-187ca89437f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-206</value>
      <webElementGuid>1477cc66-38f8-4924-a84d-6684fcb95ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CloseDate</value>
      <webElementGuid>96c858b2-348c-4b8a-baab-cce0ab025996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cd6f8836-7ebc-48b6-9f98-77fcae791b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>05065025-3732-4fbf-814b-d9c5ac7ab259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-206']</value>
      <webElementGuid>73b77065-f3e3-45ea-af58-855a480d2a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionContent-200']/div/slot/records-record-layout-row/slot/records-record-layout-item[2]/div/span/slot/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>5008ff7b-ea54-4a30-9632-b81f31e347fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
      <webElementGuid>0b6fcac0-2d6f-4685-946a-e9abc2adb289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-206' and @name = 'CloseDate']</value>
      <webElementGuid>173fb46e-ec48-44b1-8350-fc2082ea45ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
