<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-base-combobox-item_Ravishankar Nr_d16d84</name>
   <tag></tag>
   <elementGuidId>4227e65a-99ce-45aa-be48-1317225f3cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-479-1-479</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span[contains(@class,'slds-listbox__option-text')]//lightning-base-combobox-formatted-text)[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-input-479-1-479']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-base-combobox-item</value>
      <webElementGuid>c0cbfdae-303d-40fd-8dfd-00e5af741cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media slds-listbox__option slds-media_center slds-listbox__option_entity slds-has-focus</value>
      <webElementGuid>323cb559-2782-4fad-a94d-3abe78ed4ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id</name>
      <type>Main</type>
      <value>combobox-input-479-1</value>
      <webElementGuid>1bad8041-1600-49ab-8709-7100b403365f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>0053g000001GxevAAC</value>
      <webElementGuid>686c93a3-43ba-468a-9d68-0e69e0261910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6dca6ca8-0c3f-4c01-b764-fdf5565c0f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-input-479-1-479</value>
      <webElementGuid>1caa171b-4f45-44c4-ac29-395521920fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bb29963d-1f79-400f-9250-6a39fd411684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8129152f-34b9-425c-9f33-e6e54ba5c58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ravishankar Nravishankar.n@revature.com</value>
      <webElementGuid>158e7071-1560-47e5-b6ca-a8c6bd8aafe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[contains(@class,'slds-listbox__option-text')]//lightning-base-combobox-formatted-text)[1]</value>
      <webElementGuid>ecb7e046-4527-4d53-be51-3925cb91728f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-input-479-1-479']</value>
      <webElementGuid>3dbfd743-48fb-4de6-9455-425168d630da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-element-479']/ul/li/lightning-base-combobox-item</value>
      <webElementGuid>9e59e41b-08b4-46bb-8bc3-7239362122cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/lightning-base-combobox-item</value>
      <webElementGuid>cf92f532-c7a9-4c34-8b5e-8690ad3003c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id = 'combobox-input-479-1-479' and (text() = 'Ravishankar Nravishankar.n@revature.com' or . = 'Ravishankar Nravishankar.n@revature.com')]</value>
      <webElementGuid>bd423973-58f0-42a7-9ad1-8a9b489a83dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
