<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Opp_stage</name>
   <tag></tag>
   <elementGuidId>305ac257-4681-443e-8858-e2cbe697eaa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@title='Discovery']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@title='Discovery']</value>
      <webElementGuid>a627f4db-494f-4515-bf06-76a6be0f4223</webElementGuid>
   </webElementProperties>
</WebElementEntity>
