<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_C2H - 3</name>
   <tag></tag>
   <elementGuidId>f7217a20-7a79-428a-812c-ed12363140f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-335-2-335 > span.slds-media__body > span.slds-truncate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'C2H - 3' and (text() = 'C2H - 3' or . = 'C2H - 3')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-335-2-335']/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5edc9615-38a5-4634-aeb1-44dd8d0215f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate</value>
      <webElementGuid>2adcc2a2-e6a1-46b0-bc06-c0d2c22fd04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>C2H - 3</value>
      <webElementGuid>042edf6c-d5b4-4213-af34-b66fc3548a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C2H - 3</value>
      <webElementGuid>e04b7457-34eb-4e53-a329-d9661dd8ac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-335-2-335&quot;)/span[@class=&quot;slds-media__body&quot;]/span[@class=&quot;slds-truncate&quot;]</value>
      <webElementGuid>b2eb9fe6-15dd-493f-88c1-6c24f19e75f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-335-2-335']/span[2]/span</value>
      <webElementGuid>644b62b7-50f3-40c7-9c6d-94f4cc5d16bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-field[3]/slot/record_flexipage-record-field/div/div/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[3]/span[2]/span</value>
      <webElementGuid>0f324d27-db0f-40c6-8527-8d29e599d9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'C2H - 3' and (text() = 'C2H - 3' or . = 'C2H - 3')]</value>
      <webElementGuid>796b4aee-10ea-4f46-909f-ddfcf38e93c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
