<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AutoLead37 contact37 testing37</name>
   <tag></tag>
   <elementGuidId>3052c930-ac87-4c1d-9813-4f0a1a790783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-input-501-1-501 > span.slds-media__body > span.slds-listbox__option-text.slds-listbox__option-text_entity</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@class,'slds-listbox__option-text_entity')]//lightning-base-combobox-formatted-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-input-501-1-501']/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d82bd1b1-fee5-41ba-b703-8fb357104701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-listbox__option-text slds-listbox__option-text_entity</value>
      <webElementGuid>ee044ca6-0d89-4780-b589-b88a7ec53541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AutoLead37 contact37 testing37</value>
      <webElementGuid>0ade1f8a-de52-4f3e-8c1e-63f7c3ea4873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@class,'slds-listbox__option-text_entity')]//lightning-base-combobox-formatted-text</value>
      <webElementGuid>9247eef2-2cd3-4401-8f09-584a5623426e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-input-501-1-501']/span[2]/span</value>
      <webElementGuid>8701f31d-c422-4c83-a6f5-b8e751e617a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/lightning-base-combobox-item/span[2]/span</value>
      <webElementGuid>b9c3c647-a098-451d-995e-1bb0ce3d2ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AutoLead37 contact37 testing37' or . = 'AutoLead37 contact37 testing37')]</value>
      <webElementGuid>a842568e-c8e4-404e-8eaf-7313e2e4f392</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
