<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_external14 test contcat14</name>
   <tag></tag>
   <elementGuidId>b35ff2c1-8d97-41c9-b03e-7afa6c0beb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div/div/div/div/div/div[2]/div/div/div/article/div[2]/ul/li/div/a/h3/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.uiOutputText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5d7e247-4190-446b-8675-a8322d4bce35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>135:760;a</value>
      <webElementGuid>70a288d5-fa14-4b5e-8073-28692e0535b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uiOutputText</value>
      <webElementGuid>f883de4d-f156-4d3f-b586-da7dc0128ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>uiOutputText</value>
      <webElementGuid>1595de7e-ff47-4732-89be-2fb285d3b164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>external14 test contcat14</value>
      <webElementGuid>91896742-fc34-4a5d-bdcd-840ddd4815f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;container homeLanding&quot;]/div[@class=&quot;flexipagePage&quot;]/div[@class=&quot;responsiveContents homeDesktopTemplate&quot;]/div[@class=&quot;colMain&quot;]/div[@class=&quot;bottomWrapper&quot;]/div[@class=&quot;bottomLeft&quot;]/div[@class=&quot;flexipageComponent&quot;]/div[@class=&quot;recentItemsContainer flexipageRecentItems&quot;]/article[@class=&quot;slds-card slds-card_boundary forceBaseCard flexipageCard&quot;]/div[@class=&quot;slds-card__body slds-card__body--inner&quot;]/ul[1]/li[@class=&quot;light flex-item actionable uiInfiniteListRow forceActionRow forceListRecord flexipageRecentItemStencil forceRecordLayout&quot;]/div[@class=&quot;body&quot;]/a[@class=&quot;listItem&quot;]/h3[@class=&quot;itemTitle&quot;]/span[@class=&quot;uiOutputText&quot;]</value>
      <webElementGuid>417a861a-667a-47fa-8d3c-b5ebf20d1394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div/div/div/div/div/div[2]/div/div/div/article/div[2]/ul/li/div/a/h3/span</value>
      <webElementGuid>ebccf49d-24cf-4df8-8ae1-ad55932e8d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/span</value>
      <webElementGuid>3ee60b1b-96dc-4738-b1e3-530df5e51250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'external14 test contcat14' or . = 'external14 test contcat14')]</value>
      <webElementGuid>84d82cc3-8f29-4df6-8f2e-b6d6a71d585c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
