<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Start Process</name>
   <tag></tag>
   <elementGuidId>e1fa7e61-4335-4894-8870-3c56059c548c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_neutral > span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Start Process' or . = 'Start Process')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_2']/div/div/div[2]/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-external-contact___-contact___-v-i-e-w/forcegenerated-flexipage_externalcontact_contact__view_js/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[2]/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4824374d-2b4a-48b0-92b8-aa76fe29928c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1334:0</value>
      <webElementGuid>803f0164-e8ec-46fd-95ce-07ccf028a650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Process</value>
      <webElementGuid>059b5353-31d8-488e-9164-0c4f27403bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[(text() = 'Start Process' or . = 'Start Process')]</value>
      <webElementGuid>35a71990-c569-46bb-881c-98b24d147a59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[2]/div/div/one-record-home-flexipage2/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-external-contact___-contact___-v-i-e-w/forcegenerated-flexipage_externalcontact_contact__view_js/record_flexipage-desktop-record-page-decorator/div/records-record-layout-event-broker/slot/slot/flexipage-record-home-template-desktop2/div/div[2]/div[2]/slot/flexipage-component2/slot/flexipage-aura-wrapper/div/div/div/button/span</value>
      <webElementGuid>5ebbc8fe-4b95-4c25-bc71-3b045c278aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flexipage-aura-wrapper/div/div/div/button/span</value>
      <webElementGuid>03910b8c-eb52-42d6-a246-daf4e892e5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Start Process' or . = 'Start Process')]</value>
      <webElementGuid>268412d9-d32f-4e8c-8248-dac4d02c8830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
